spring:
  application:
    name: rest-assured-demo
    webflux:
      static-path-pattern: "/**"
    resources:
      static-locations: "classpath:/public-web-resources/"
  jackson:
      serialization:
        write-dates-as-timestamps: false
        fail-on-empty-beans: false
      date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
      default-property-inclusion: non_null

swagger:
  basePath: /
  host: localhost:8080

doc:
  root-url: http://localhost:8080/swagger-ui.html

logging:
  level:
    org.springframework.web: ERROR
    za.co.minions.loans: DEBUG
    org.springframework.webflux: DEBUG
    reactor.ipc.netty.channel.ChannelOperationsHandler: DEBUG
    reactor.ipc.netty.http.server.HttpServer: DEBUG
    reactor.ipc.netty.http.client: DEBUG
    io.reactivex.netty.protocol.http.client: DEBUG
    io.netty.handler: DEBUG
    io.netty.handler.proxy.HttpProxyHandler: DEBUG
    io.netty.handler.proxy.ProxyHandler: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    reactor.ipc.netty.channel: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread][%X{X-B3-TraceId:-}, %X{X-B3-SpanId:-}, %X{X-B3-ParentSpanId:-}] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread][%X{X-B3-TraceId:-}, %X{X-B3-SpanId:-}, %X{X-B3-ParentSpanId:-}] %-5level %logger{36} - %msg%n"
  file: loans.log


