openapi: "3.1.0"
info:
  title: "Aksjonær i virksomhet API"
  version: 1.1.0
  description: "Tjenesten leverer informasjon om en virksomhets aksjonærer pr. 31.12 sist kalenderår."
  termsOfService: "https://www.skatteetaten.no/deling/bruksvilkar-for-delingstjenester"
  contact:
    name: "Brukerstøtte"
    url: "https://www.skatteetaten.no/deling/kontakt/"
externalDocs:
  description: "Dokumentasjon på Skatteetatens GitHub"
  url: "https://skatteetaten.github.io/api-dokumentasjon/api/aksjonaer"
servers:
- url: "https://aksjonaerivirksomhet.api.skatteetaten-test.no/v1"
  description: "Ekstern deling (Test)"
- url: "https://aksjonaerivirksomhet.api.skatteetaten.no/v1"
  description: "Produksjon (Prod)"
components:
  schemas:
    Feil:
      description: "Feilstruktur for alle feilmeldinger."
      type: "object"
      properties:
        kode:
          type: "string"
          description: "Feilkode, for maskinell håndtering"
          examples:
          - "AIV-0xx"
        melding:
          type: "string"
          description: "Beskrivelse av feilen som har oppstått"
          examples:
          - "Fant ikke gitt identifikator"
        korrelasjonsid:
          type: "string"
          description: "Korrelasjonsid"
          examples:
          - "123e4567-e89b-12d3-a456-426655440000"
    Aksjeselskap:
      type: "object"
      description: ""
      properties:
        aksjonaerer:
          type: "array"
          description: ""
          items:
            $ref: "#/components/schemas/Aksjonaer"
        totaltAntallAksjer:
          description: ""
          $ref: "#/components/schemas/Antall"
        identifikator:
          description: "Organisasjonsnummeret til aksjeselskapet det ble søkt på."
          $ref: "#/components/schemas/NorskIdentifikator"
        kalenderaar:
          description: "Kalenderåret det ble søkt på."
          $ref: "#/components/schemas/Aarstall"
    Aksje:
      type: "object"
      description: ""
      properties:
        isinnummer:
          description: ""
          $ref: "#/components/schemas/Tekst"
        antallAksjer:
          description: ""
          $ref: "#/components/schemas/Antall"
        aksjeklasse:
          description: "(<a href='https://data.skatteetaten.no/begrep/1e333067-6837-11e6-a7ce-fac03dffe1d7'>Begrepsreferanse</a>)"
          $ref: "#/components/schemas/Aksjeklasse"
    Aksjonaer:
      type: "object"
      description: "(<a href='https://data.skatteetaten.no/begrep/20b2e177-9fe1-11e5-a9f8-e4115b280940'>Begrepsreferanse</a>)"
      properties:
        personidentifikator:
          description: ""
          $ref: "#/components/schemas/Foedselsnummer"
        organisasjonsnummer:
          description: ""
          $ref: "#/components/schemas/Organisasjonsnummer"
        navn:
          description: "Person eller organisasjonsnavn"
          $ref: "#/components/schemas/Tekst"
        foedselsaar:
          description: ""
          $ref: "#/components/schemas/Aarstall"
        postnummer:
          description: ""
          $ref: "#/components/schemas/Postnummer"
        aksjer:
          type: "array"
          description: ""
          items:
            $ref: "#/components/schemas/Aksje"
        landkode:
          description: ""
          $ref: "#/components/schemas/Landkode"
    Antall:
      type: "integer"
      description: "mengde som utgjør eller kan uttrykkes i et visst tall (<a href='https://data.skatteetaten.no/begrep/20b2e145-9fe1-11e5-a9f8-e4115b280940'>Begrepsreferanse</a>)"
      format: "int64"
    NorskIdentifikator:
      type: "string"
      description: "(<a href='https://data.skatteetaten.no/begreper/dcfb4778-e484-11e6-9cb3-005056821322'>Begrepsreferanse</a>)"
    Aarstall:
      type: "string"
      description: "årstall er et tall som angir årets nummer i tidsregningen i den gregorianske kalender (<a href='https://data.skatteetaten.no/begrep/20b2e14a-9fe1-11e5-a9f8-e4115b280940'>Begrepsreferanse</a>)"
      format: "year"
    Tekst:
      type: "string"
      description: "vilkårlig lang sekvens av tegn inkludert aksenter og spesielle tegn fra standardiserte tegnsett (<a href='https://data.skatteetaten.no/begrep/20b52af3-9fe1-11e5-a9f8-e4115b280940'>Begrepsreferanse</a>)"
      maxLength: 4000
    Aksjeklasse:
      type: "string"
      description: "Lovlige verdier for kodelisten ligger her: https://skatteetaten.github.io/api-dokumentasjon/download/aksjeklasse_kodeliste.xml (<a href='https://skatteetaten.github.io/api-dokumentasjon/download/aksjeklasse_kodeliste.xml'>Kodelistereferanse</a>)"
    Foedselsnummer:
      type: "string"
      description: "ellevesifret identifikasjonsnummer for personer bosatt i Norge, der de seks første sifrene angir fødselsdato og de fem siste personnummer. (<a href='https://data.skatteetaten.no/begrep/5138da10-be20-11e6-8004-005056825ca0'>Begrepsreferanse</a>)"
      minLength: 11
      pattern: "[0-9]+"
      maxLength: 11
    Organisasjonsnummer:
      type: "string"
      description: "9 sifret nummer gitt de som er registrert i Enhetsregisteret. (<a href='https://data.skatteetaten.no/begrep/20b2e1a8-9fe1-11e5-a9f8-e4115b280940'>Begrepsreferanse</a>)"
      minLength: 9
      pattern: "[0-9]+"
      maxLength: 9
    Postnummer:
      type: "string"
      description: "nummer på et poststed (<a href='https://data.skatteetaten.no/begrep/20b2e121-9fe1-11e5-a9f8-e4115b280940'>Begrepsreferanse</a>)"
      minLength: 4
      pattern: "([0-9]){4}"
      maxLength: 4
    Landkode:
      type: "string"
      description: "koder for land etter ISO 3166-1 Alpha-2 (<a href='https://data.skatteetaten.no/begrep/20b2e112-9fe1-11e5-a9f8-e4115b280940'>Begrepsreferanse</a>)"
      minLength: 2
      pattern: "([A-Z]){2}"
      maxLength: 2
paths:
  /{rettighetspakke}/aksjonaerer/{organisasjonsnummer}:
    get:
      summary: "Hent aksjonærer i en virksomhet"
      description: "Informasjon om en virksomhets aksjonærer pr. 31.12 sist kalenderår"
      operationId: "hentAksjonaerIVirksomhet"
      tags:
      - "aksjonaerIVirksomhet"
      parameters:
      - name: "rettighetspakke"
        in: "path"
        description: "Datakonsumenter plasseres i en rettighetspakke (per datasett) basert på en juridisk vurdering. Rettighetspakken styrer skjermingsregler, filtrering og detaljering som benyttes når det gis innsyn i data i datasett."
        required: true
        schema:
          type: "string"
      - name: "organisasjonsnummer"
        in: "path"
        description: "Organisasjonsnummer for virksomhet"
        required: true
        schema:
          type: "string"
          examples:
          - "123456789"
      - name: "kalenderaar"
        in: "query"
        description: "Kalenderåret det skal hentes opplysninger fra. Returnerer siste tilgjengelige dersom ikke oppgitt."
        required: false
        schema:
          type: "string"
          examples:
          - "2022"
      - name: "Korrelasjonsid"
        in: "header"
        description: "Korrelasjonsid, unik identifikator for den tekniske forespørselen. Må være på UUID-format"
        required: false
        schema:
          type: "string"
          format: "uuid"
          examples:
          - "123e4567-e89b-12d3-a456-426655440000"
      responses:
        "200":
          description: "Gyldig respons"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Aksjeselskap"
        default:
          description: "Diverse feilmeldinger, se egen dokumentasjon"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feil"