openapi: 3.1.0
info:
  title: Boom API
  version : 1.0.0 
  description: |-
      ## Base URL

      The base URL for all API requests is:

      `http://104.42.44.252/BoomAPI/api/Genric`

      ## Errors

      This API uses the following error codes:

      - `100 Success`
      - `101 User Request Error`
      - `102 Error` 
      ------
servers:
  - url: http://104.42.44.252/BoomAPI/api/Genric
paths:
  /BoomInstantActivation:
    post:
      tags:
        - Instant Activation
      summary: 
      description: 
                   <h1>Description</h1>
                    <h3>The "Activate Mdn with eSim / physical sim" API activates new number for a customer using eSim or physical sim. The new number can be activated only after a  successful validation which checks if the IMEI is valid and compatible to eSim technology or not.<h3>
                    
                    <h1>Endpoints</h1>
                    <h4>/BoomInstantActivation</h4>
                    
                    <h1>Request Type</h1>
                    <h4>Post</h4>

                    <h2>Parameters</h2>
                    <ul>
                    <li><strong>ClientCode</strong> (String - Mandatory)</li>
                    <li><strong>IMEI</strong> (String - Mandatory) IMEI length Can't be greater than 16 and less than 14.</li>
                    <li><strong>SerialNumber</strong> (String - with eSim mandatory otherwise optional) Serial No. Can't be greater than 23 or less than 18.</li>
                    <li><strong>PortMobileNo</strong> (String - for portin mandatory otherwise optional)</li>
                    <li><strong>Carrrier_Type</strong> (Int - Mandatory) 97 for purple2 and 90 for red.</li>
                    <li><strong>TariffId</strong> (Int - Mandatory)</li>
                    <li><strong>Month</strong> (Int - Mandatory)</li>
                    <li><strong>Rental</strong> (decimal - Mandatory)</li>
                    <li><strong>isWifi</strong> (bool - Mandatory) True- with Wi-Fi and False- without Wi-Fi.</li>
                    <li><strong>TransactionId</strong> (String - Mandatory) Starting from “BRI” for instant activation.</li>
                    <li><strong>ActivationOrPortin</strong> (Int - Mandatory) 0 for Activation and 1 for Portin.</li>
                    <li><strong>Customer_Details</strong> (Object - Mandatory)
                    <ul>
                    <li><strong>Firstname</strong> (String - Mandatory)</li>
                    <li><strong>LastName</strong> (String - Mandatory)</li>
                    <li><strong>Email</strong> (String - Optional)</li>
                    <li><strong>Address</strong> (String - Mandatory)</li>
                    <li><strong>City</strong> (String - Mandatory)</li>
                    <li><strong>State</strong> (String - Mandatory)</li>
                    <li><strong>Zip</strong> (String - Mandatory)</li>
                    <li><strong>contactNumber</strong> (String - for portin mandatory otherwise optional) Port contact no can only be 10 digits.</li>
                   </ul>
                   </li>
                   </ul>
      operationId: add Mdn
      requestBody:
        description: Add Activation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InstantActivationRequest'
        required: true
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
  /BoomRecharge:
    post:
      tags:
        - Recharge
      summary: 
      description:  
                    <h1>Description</h1>
                    <h3>The "Recharge by Mdn" API is a specific type of recharge API that allows users to recharge their mobile phone using their Mdn.<h3>
                    
                    <h1>Endpoints</h1>
                    <h4>/BoomRecharge</h4>
                    
                    <h1>Request Type</h1>
                    <h4>Post</h4>

                    <h3>Parameters</h3>
                    <ul>
                    <li><code>ClientCode</code> (String - Mandatory)</li>
                    <li><code>TransactionId</code> (String - Mandatory) Starting with "BRI" for instant activation.</li>
                    <li><code>MSISDN</code> (String - Mandatory) MSISDN must be exactly 10 digits.</li>
                    <li><code>PlanID</code> (String - Mandatory)</li>
                    <li><code>Rental</code> (Decimal - Mandatory)</li>
                    <li><code>Carrier_Type</code> (Int - Mandatory) 97 for purple2 and 90 for red.</li>
                    <li><code>RechargeType</code> (Int - Mandatory) 0 for after plan expires and 1 for starting from.</li>
                    </ul>
      operationId:  
      requestBody:
        description: Add Recharge
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RechargeRequest'
        required: true
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
  /BoomCheckPortinMdn:
    post:
      tags:
        - Check Portin Mdn
      summary: 
      description: 
                    <h1>Description</h1>
                    <h3>The "Check Port in by Mdn" API check if IMEI, SIM and MDN are compatible. We get status which describes if the MDN is Portable.
                    This API is called during the port in number flow to check port possibility. 
                    <h3>
                    
                    <h1>Endpoints</h1>
                    <h4>/BoomCheckPortinMdn</h4>
                    
                    <h1>Request Type</h1>
                    <h4>Post</h4>

                    <h3>Parameters</h3>
                    <ul>
                    <li><strong>ClientCode</strong> (String - Mandatory)</li>
                    <li><strong>IMEI</strong> (String - Mandatory) IMEI length must be between 14 and 16 characters.</li>
                    <li><strong>SerialNumber</strong> (String - with eSIM mandatory, otherwise optional) Serial No. must be between 18 and 23 characters.</li>
                    <li><strong>Msisdn</strong> (String - Mandatory) MSISDN must be exactly 10 digits.</li>
                    <li><strong>is4g</strong> (Boolean - for portin mandatory, otherwise optional) True with 4G and False without 4G.</li>
                    </ul>
      requestBody:
        description: Check Portin by Mdn
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckPortinMdnRequest'
        required: true
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'            
  /BoomGetMdnStatus:
    post:
      tags:
        - Get Details By Mdn
      summary: 
      description: 
      requestBody:
        description: 
                     <h1>Description</h1>
                     <h3>The "Get Details By Mdn" Api displays information about Mdn’s details, subscription details, customer details and plan.  
                     <h3>
                    
                     <h1>Endpoints</h1>
                     <h4>/BoomGetMdnStatus</h4>
                    
                     <h1>Request Type</h1>
                     <h4>Post</h4>

                     <h3>Parameters</h3>
                     <ul>
                     <li><strong>ClientCode</strong> (String - Mandatory)</li>
                     <li><strong>Msisdn</strong> (String - Mandatory) MSISDN must be exactly 10 digits.</li>
                     <li><strong>Carrier_Type</strong> (Int - Mandatory) 97 for purple2 and 90 for red.</li>
                     </ul>
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetDetailsByMdnRequest'
        required: true
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'                   
  /BoomCheckPortinStatus:
    post:
      tags:
        - Check Portin Status
      summary: 
      description: 
      requestBody:
        description: 
                     <h1>Description</h1>
                     <h3>The "Check Port-in Status by Mdn" API allows users to inquire about the port-in status of a mobile number (Mdn) 
                     when transferring their phone number from one telecommunication service provider to another. Porting, or number portability, 
                     enables users to keep their existing phone number when switching to a new provider.   
                     <h3>
                    
                     <h1>Endpoints</h1>
                     <h4>/BoomCheckPortinStatus</h4>
                    
                     <h1>Request Type</h1>
                     <h4>Post</h4>

                     <h3>Parameters</h3>
                     <ul>
                     <li><strong>ClientCode</strong> (String - Mandatory)</li>
                     <li><strong>Msisdn</strong> (String - Mandatory) MSISDN must be exactly 10 digits.</li>
                     <li><strong>Carrier_Type</strong> (Int - Mandatory) 97 for purple2 and 90 for red.</li>
                     </ul>
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckPortinStatusRequest'
        required: true
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'                                   
  /BoomCheckIMEI:
    post:
      tags:
        - Check IMEI
      summary: 
      description: 
      requestBody:
        description:
                     <h1>Description</h1>
                     <h3>The "Check by IMEI" API designed to provide information about the validity and status of an International Mobile 
                     Equipment Identity (IMEI) number. IMEI validity can refer to various aspects such as whether the device associated with the IMEI 
                     is legitimate.  
                     <h3>
                    
                     <h1>Endpoints</h1>
                     <h4>/BoomCheckImei</h4>
                    
                     <h1>Request Type</h1>
                     <h4>Post</h4>

                     <h3>Parameters</h3>
                     <ul>
                     <li><strong>ClientCode</strong> (String - Mandatory)</li>
                     <li><strong>IMEI</strong> (String - Mandatory) IMEI length must be between 14 and 16 characters.</li>
                     <li><strong>Carrier_Type</strong> (Int - Mandatory) 97 for purple2 and 90 for red.</li>
                     <li><strong>is4g</strong> (Boolean - Mandatory) True with 4G and False without 4G.</li>
                     </ul>
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckIMEIRequest'
        required: true
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'                    
  /BoomCheckSerialNumber:
    post:
      tags:
        - Check Serial Number
      summary: 
      description: 
      requestBody:
        description:
                     <h1>Description</h1>
                     <h3>The "Check by Serial Number" API designed to provide information about the validity of a SIM card based on its     
                     serial number. SIM card validity can refer to various aspects such as whether the SIM card is active.   
                     <h3>
                    
                     <h1>Endpoints</h1>
                     <h4>/BoomCheckSerialNumber</h4>
                    
                     <h1>Request Type</h1>
                     <h4>Post</h4>

                     <h3>Parameters</h3>
                     <ul>
                     <li><strong>ClientCode</strong> (String - Mandatory)</li>
                     <li><strong>SerialNumber</strong> (String - Mandatory) Serial No. must be between 18 and 23 characters.</li>
                     <li><strong>Carrier_Type</strong> (Int - Mandatory) 97 for purple2 and 90 for red.</li>
                     </ul>
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckSerialNumberRequest'
        required: true
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'                                
components:
  schemas:
    Customer_Details:
      type: object
      properties:
        firstName:
          type: string
          format: ""
          example: "TestDemoCustomer"
        lastName:
          type: string
          example: "TestDemoCustomer"
        email:
          type: string
          format: ""
          example: "testdemo@customer.com"
        address:
          type: string
          example: "21 Main St"
        city:
          type: string
          format: ""
          example: "Chester"
        state:
          type: string
          example: "MA"
        zip:
          type: string
          format: ""
          example: "01011"
        contactNumber:
          type: string
          example: "9988776655"  
        portableFromProvider:
          type: string
          example: "test"
        portableFromAccountNumber:
          type: string
          format: ""
          example: "554433223333" 
        portableFromAccountPassCode:
          type: string
          example: "01011"       
      xml:
        name: Customer_Details
    InstantActivationRequest:
      required:
        - name
        - photoUrls
      type: object
      properties:
        ClientCode:
          type: string
          example: "xx"
        IMEI:
          type: string
          example: "xx"
        SerialNumber:
          type: string
          example: "xx"  
        PortMobileNo:
          type: string
          example: "xx"    
        Carrrier_Type:
          type: integer
          example: 97
        TariffId:
          type: string
          example: "1"
        Month:
          type: integer
          example: 1  
        Rental:
          type: integer
          example: 3  
        isWifi:
          type: boolean
          example: false
        isEsim:
          type: boolean
          example: false
        TransactionId:
          type: integer
          example: "xx"  
        ActivationOrPortin:
          type: integer
          example: 0   
        Customer_Details:
          $ref: '#/components/schemas/Customer_Details'
      xml:
        name: pet  
    RechargeRequest:
      required:
        - name
        - photoUrls
      type: object
      properties:
        ClientCode:
          type: string
          example: "xx"
        TransactionId:
          type: string
          example: "xx"
        MSISDN:
          type: string
          example: "9999988888"  
        PlanID:
          type: string
          example: "1"    
        Rental:
          type: number
          example: 3
        Carrier_Type:
          type: integer
          example: 90
        RechargeType:
          type: integer
          example: 0 
      xml:
        name: pet      
    CheckPortinMdnRequest:
      required:
        - name
        - photoUrls
      type: object
      properties:
        ClientCode:
          type: string
          example: "xx"
        Imei:
          type: string
          example: "xx"
        SerialNumber:
          type: string
          example: "xx"  
        Msisdn:
          type: string
          example: "xx"    
        Carrier_Type:
          type: integer
          example: 90
      xml:
        name: pet          
    GetDetailsByMdnRequest:
      required:
        - name
        - photoUrls
      type: object
      properties:
        ClientCode:
          type: string
          example: "xx"
        Msisdn:
          type: string
          example: "xx"    
        Carrier_Type:
          type: integer
          example: 90
      xml:
        name: pet              
    CheckPortinStatusRequest:
      required:
        - name
        - photoUrls
      type: object
      properties:
        ClientCode:
          type: string
          example: "xx"
        Msisdn:
          type: string
          example: "xxx"    
        Carrier_Type:
          type: integer
          example: 90
      xml:
        name: pet                  
    CheckIMEIRequest:
      required:
        - name
        - photoUrls
      type: object
      properties:
        ClientCode:
          type: string
          example: "xx"
        Imei:
          type: string
          example: "xx"    
        Carrier_Type:
          type: integer
          example: 90
        is4g:
          type: boolean
          example: false  
      xml:
        name: pet                      
    CheckSerialNumberRequest:
      required:
        - name
        - photoUrls
      type: object
      properties:
        ClientCode:
          type: string
          example: "xxx"
        SerialNumber:
          type: string
          example: "xxx"    
        Carrier_Type:
          type: integer
          example: 90
      xml:
        name: pet                          
    ApiResponse:
      type: object
      properties:
        errorcode:
          type: string
          format: ""
          example: 101
        data:
          type: string
          example: null
        details:
          type: string
          example: string
        status:
          type: boolean  
      xml:
        name: '##default'           

    GetDetailsByMdnApiResponse:
      type: object
      properties:
        errorcode:
          type: string
          format: ""
          example: 101
        data:
          type: string
          example: null
        details:
          type: string
          example: string
        creationTime:
          type: string
          example: null
        delayActivation:
          type: boolean
          example: false  
        status:
          type: boolean  
      xml:
        name: '##default2'