openapi: 3.0.1
info:
  description: Loans API
  title: Loans API
  version: "2.0"
servers:
- url: //localhost:8080/
tags:
- description: Loans API
  name: Loans
paths:
  /loans:
    post:
      deprecated: false
      description: One loan application request supported in the body.
      operationId: applyForALoanUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanRequest'
        description: loanRequest
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoanResponse'
          description: OK
      summary: Apply for a loan
      tags:
      - Loans
      x-codegen-request-body-name: loanRequest
      x-content-type: application/json
      x-accepts: application/json
components:
  schemas:
    BankAccount:
      example:
        bankName: SCRUM_BANK
        accountNumber: "1234567890"
      properties:
        accountNumber:
          description: Account number
          example: "1234567890"
          type: string
        bankName:
          description: Name of the bank
          enum:
          - SCRUM_BANK
          - ICONIC_BANK
          - MINIONS_BANK
          - MOLEWA_BANK
          type: string
      title: BankAccount
      type: object
    LoanRequest:
      example:
        bankAccount:
          bankName: SCRUM_BANK
          accountNumber: "1234567890"
        surname: Molewa
        name: Pontsho
        idNumber: "9901025391084"
      properties:
        bankAccount:
          $ref: '#/components/schemas/BankAccount'
        idNumber:
          description: ID Number of the applicant
          example: "9901025391084"
          type: string
        name:
          description: Name of the applicant
          example: Pontsho
          type: string
        surname:
          description: surname of the applicant
          example: Molewa
          type: string
      title: LoanRequest
      type: object
    LoanResponse:
      example:
        reference: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        warnings:
        - warnings
        - warnings
        validationStatus: false
        errors:
        - errors
        - errors
      properties:
        errors:
          description: Validation errors
          items:
            type: string
          type: array
        reference:
          description: Generated reference number for you application
          format: uuid
          type: string
        validationStatus:
          description: Indicates whether the validation is a success/failure
          example: false
          type: boolean
        warnings:
          description: Validation warnings
          items:
            type: string
          type: array
      required:
      - validationStatus
      title: LoanResponse
      type: object
x-original-swagger-version: "2.0"

