openapi: 3.1.0
info:
  contact:
    email: kendrick@us.ibm.com
  description: |2-


    Some useful links:
    - [Distribution API Wiki](https://github.com/wiki)
    - [Distribution API Source](https://github.com/distribution-api/)
  license:
    name: IBM Commercial
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: internal
  title: IBM Cloud Video - Distributions API
  version: 1.0.1
externalDocs:
  url: http://wiki.com
servers:
- url: https://petstore3.swagger.io/api/v3
tags:
- description: "Distribution Operations limited to finding by schedule/channel id\
    \ + asset id, fetching a distribution by ID and deleting a Distribution by ID"
  name: distributions
- description: "Distribution Operations limited to finding by schedule/channel id\
    \ + asset id, fetching a distribution by ID and deleting a Distribution by ID"
  name: Future
paths:
  /distributions/{id}:
    delete:
      operationId: deleteDistribution
      parameters:
      - description: ID of the distribution to be deleted
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: Invalid Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: Distribution not found
      summary: Delete user
      tags:
      - distributions
      x-accepts: "application/json,application/xml"
    get:
      description: ""
      operationId: getDistributionById
      parameters:
      - description: Unique Numerical ID of the distribution
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Distribution'
            application/xml:
              schema:
                $ref: '#/components/schemas/Distribution'
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: Invalid Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: Distribution not found
      summary: Get Distribution by Id
      tags:
      - distributions
      x-accepts: "application/json,application/xml"
  /distributions/channels/{channelId}:
    get:
      description: ""
      operationId: findChannelDistributionByAssetId
      parameters:
      - description: Unique Numerical ID of the distribution
        explode: false
        in: path
        name: channelId
        required: true
        schema:
          type: integer
        style: simple
      - description: Unique Numerical ID of the distribution
        explode: true
        in: query
        name: assetId
        required: true
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Distribution'
            application/xml:
              schema:
                $ref: '#/components/schemas/Distribution'
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: Invalid Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: Distribution not found
      summary: Get Distribution by Id
      tags:
      - distributions
      x-accepts: "application/json,application/xml"
  /distributions/schedules/{scheduleId}:
    get:
      description: ""
      operationId: findScheduleDistributionByAssetId
      parameters:
      - description: Unique Numerical ID of the distribution
        explode: false
        in: path
        name: scheduleId
        required: true
        schema:
          type: integer
        style: simple
      - description: Unique Numerical ID of the distribution
        explode: true
        in: query
        name: assetId
        required: true
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Distribution'
            application/xml:
              schema:
                $ref: '#/components/schemas/Distribution'
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: Invalid Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: Distribution not found
      summary: Get Distribution by Id
      tags:
      - distributions
      x-accepts: "application/json,application/xml"
  /distributions/:
    get:
      description: ""
      operationId: listDistributions
      parameters:
      - description: Start at offset (paging)
        explode: true
        in: query
        name: index
        required: true
        schema:
          type: integer
        style: form
      - description: Max returned (paging)
        explode: true
        in: query
        name: max
        required: true
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Distributions'
            application/xml:
              schema:
                $ref: '#/components/schemas/Distributions'
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: Invalid Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: Distribution not found
      summary: List Distributions
      tags:
      - Future
      x-accepts: "application/json,application/xml"
components:
  requestBodies:
    Distribution:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Distribution'
        application/xml:
          schema:
            $ref: '#/components/schemas/Distribution'
  schemas:
    Distribution:
      example:
        requiredBy: 2000-01-23T04:56:07.000+00:00
        created: 2000-01-23T04:56:07.000+00:00
        channel:
          name: IBM - Foo Affiliate
          id: "0981234"
        priority: 1900.0
        message: "Unable to connect to ip: XXX.XXX.XXX.XXX"
        retries: 0
        slaDate: 2000-01-23T04:56:07.000+00:00
        fileTransfers:
        - id: 108146209
          state: SENT
          message: message
          uri: s3://vlm-cloud-mock-bucket/assets/999999/IBMV0021597300000000-35007745.mpg
        - id: 108146209
          state: SENT
          message: message
          uri: s3://vlm-cloud-mock-bucket/assets/999999/IBMV0021597300000000-35007745.mpg
        id: 522411622
        state: complete
        asset:
          name: IBMV0021597300000000
          id: 1409609
        updated: updated
        scheduleId: 777777
        account:
          name: IBM Cloud Video
          id: 969696
      properties:
        id:
          example: 522411622
          format: int64
          type: integer
        asset:
          $ref: '#/components/schemas/Asset'
        scheduleId:
          example: 777777
          format: int64
          type: integer
        channel:
          $ref: '#/components/schemas/Channel'
        account:
          $ref: '#/components/schemas/Account'
        priority:
          example: 1900.0
          type: number
        created:
          format: date-time
          type: string
        updated:
          type: string
          fotrmat: date-time
        requiredBy:
          format: date-time
          type: string
        slaDate:
          format: date-time
          type: string
        state:
          description: Distribution Status
          enum:
          - UNKNOWN
          - INITIATING
          - WAITING_FOR_FILE_TRANSFER
          - CONTENT_ERROR
          - TRANSFER_ERROR
          - SCHEDULED_FOR_TRANSFER
          - TRANSFERRING
          - TRANSFERRED
          - EXPORT_ERROR
          - SCHEDULED_FOR_EXPORT
          - EXPORTING
          - EXPORTED
          - SCHEDULED_FOR_DELETE
          - DELETING
          - DELETED
          - DELETE_ERROR
          - API_ERROR
          - MDU_HOLD
          - MDU_HOLD_REJECT
          - MDU_HOLD_APPROVED
          example: complete
          type: string
        fileTransfers:
          items:
            $ref: '#/components/schemas/Transfer'
          type: array
          xml:
            wrapped: true
        message:
          example: "Unable to connect to ip: XXX.XXX.XXX.XXX"
          type: string
        retries:
          format: int32
          type: integer
      required:
      - account
      - asset
      - channel
      - created
      - id
      - scheduleId
      - state
      xml:
        name: distribution
    Asset:
      example:
        name: IBMV0021597300000000
        id: 1409609
      properties:
        id:
          example: 1409609
          format: int64
          type: integer
        name:
          example: IBMV0021597300000000
          type: string
      required:
      - id
      - name
      xml:
        name: asset
    Account:
      example:
        name: IBM Cloud Video
        id: 969696
      properties:
        id:
          example: 969696
          format: int64
          type: integer
        name:
          example: IBM Cloud Video
          type: string
      required:
      - id
      - name
      xml:
        name: account
    Channel:
      example:
        name: IBM - Foo Affiliate
        id: "0981234"
      properties:
        id:
          example: "0981234"
          format: int64
          type: integer
        name:
          example: IBM - Foo Affiliate
          type: string
      required:
      - id
      - name
      xml:
        name: channel
    Transfer:
      example:
        id: 108146209
        state: SENT
        message: message
        uri: s3://vlm-cloud-mock-bucket/assets/999999/IBMV0021597300000000-35007745.mpg
      properties:
        id:
          description: File Transfer Id
          example: 108146209
          format: int64
          type: integer
        uri:
          description: Uri Resolving to the content in s3 (s3 uri)
          example: s3://vlm-cloud-mock-bucket/assets/999999/IBMV0021597300000000-35007745.mpg
          type: string
        state:
          description: File Transfer State
          enum:
          - UNKNOWN
          - WAITING_FOR_CONTENT_COMPLETION
          - SEND_ERROR
          - SCHEDULED_FOR_SEND
          - SENDING
          - SENT
          - ABORTED
          - EXPORT_ERROR
          - SCHEDULED_FOR_EXPORT
          - EXPORTING
          - EXPORTED
          example: SENT
          type: string
        message:
          type: string
      required:
      - id
      - state
      - uri
      xml:
        name: fileTransfer
    Transfers:
      items:
        $ref: '#/components/schemas/Transfer'
      type: array
      xml:
        wrapped: true
    Distributions:
      items:
        $ref: '#/components/schemas/Distribution'
      type: array
      xml:
        wrapped: true
    ApiResponse:
      example:
        code: 6
        error: error
        message: message
      properties:
        code:
          format: int32
          type: integer
        error:
          type: string
        message:
          type: string
      required:
      - code
      - error
      xml:
        name: error
  securitySchemes:
    api_key:
      in: header
      name: api_key
      type: apiKey

