openapi: 3.0.0
info:
  title: Mighty Claim Helper API
  version: v1
servers:
- url: /
paths:
  /initialize:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_initialize_post_request'
        required: true
      responses:
        "200":
          description: Initial greeting and preliminary questions.
      summary: Start a new user session with an initial greeting.
      x-content-type: application/json
      x-accepts: application/json
  /consent-verification:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_consent_verification_post_request'
        required: true
      responses:
        "200":
          description: Confirmation of consent verification.
      summary: Verify user consent for communication via text (SMS).
      x-content-type: application/json
      x-accepts: application/json
  /consent-confirmation-disclaimer:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_consent_confirmation_disclaimer_post_request'
        required: true
      responses:
        "200":
          description: Confirmation of user's understanding and consent.
      summary: Confirm user's understanding of the service's nature and limitations.
      x-content-type: application/json
      x-accepts: application/json
  /basic-user-info:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_basic_user_info_post_request'
        required: true
      responses:
        "200":
          description: Request for basic user information.
      summary: Collect basic user information like full name and referral source.
      x-content-type: application/json
      x-accepts: application/json
  /case-specific-queries:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_basic_user_info_post_request'
        required: true
      responses:
        "200":
          description: Case-specific queries and potential off-ramp scenarios.
      summary: Ask case-specific questions regarding legal representation and accident
        details.
      x-content-type: application/json
      x-accepts: application/json
  /follow-up-questions:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_follow_up_questions_post_request'
        required: true
      responses:
        "200":
          description: Follow-up questions for clarity and completeness.
      summary: Pose detailed follow-up questions based on previous responses.
      x-content-type: application/json
      x-accepts: application/json
  /business-hours-notification:
    get:
      responses:
        "200":
          description: Business hours information.
      summary: Notify the user about business hours and expected response times.
      x-accepts: application/json
  /end-interaction:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_basic_user_info_post_request'
        required: true
      responses:
        "200":
          description: Thank you message and interaction conclusion.
      summary: Conclude the interaction and provide closure.
      x-content-type: application/json
      x-accepts: application/json
  /feedback-collection:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_feedback_collection_post_request'
        required: true
      responses:
        "200":
          description: Acknowledgement of feedback and appreciation.
      summary: Collect user feedback for continuous improvement.
      x-content-type: application/json
      x-accepts: application/json
components:
  schemas:
    _follow_up_questions_post_request:
      properties:
        sessionId:
          description: Session identifier.
          type: string
        userResponse:
          description: User's response to previous questions.
          type: string
      type: object
    _feedback_collection_post_request:
      properties:
        sessionId:
          description: Session identifier.
          type: string
        feedback:
          description: User's feedback on the interaction.
          type: string
      type: object
    _consent_confirmation_disclaimer_post_request:
      properties:
        sessionId:
          description: Session identifier.
          type: string
        userResponse:
          description: User's response to the disclaimer.
          type: string
      type: object
    _basic_user_info_post_request:
      properties:
        sessionId:
          description: Session identifier.
          type: string
      type: object
    _initialize_post_request:
      properties:
        sessionId:
          description: Unique identifier for the user's session.
          type: string
      type: object
    _consent_verification_post_request:
      properties:
        sessionId:
          description: Session identifier.
          type: string
        userResponse:
          description: User's response to the consent query.
          type: string
      type: object

