openapi: 3.1.0
info:
  description: crud usuários
  title: Api de cadastro de usuários
  version: 1.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/laurourbano/APIusers/1.0.1
paths:
  /users-list:
    get:
      responses:
        "200":
          description: Lista de users
      summary: Retorna todos os users
      x-accepts: application/json
  /users-list/{codigo}:
    get:
      parameters:
      - explode: false
        in: path
        name: codigo
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: User encontrado
        "404":
          description: User não encontrado
      summary: Retorna um user por código
      x-accepts: application/json
  /users-post:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "201":
          description: User criado com sucesso
        "400":
          description: Dados inválidos
      summary: Cria um novo User
      x-content-type: application/json
      x-accepts: application/json
  /users-edit/{codigo}/atualizar:
    put:
      parameters:
      - explode: false
        in: path
        name: codigo
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "200":
          description: User atualizado com sucesso
        "404":
          description: User não encontrado
        "400":
          description: Dados inválidos
      summary: Atualiza um User por código
      x-content-type: application/json
      x-accepts: application/json
  /users-delete/{codigo}/excluir:
    delete:
      parameters:
      - explode: false
        in: path
        name: codigo
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: User excluído com sucesso
        "404":
          description: User não encontrado
      summary: Exclui um User por código
      x-accepts: application/json
components:
  schemas:
    User:
      example:
        name: name
        email: email
      properties:
        name:
          type: string
        email:
          type: string

