openapi: 3.1.0
info:
  description: The API to be used by digital certificate websites in the Filedgr format
  title: FiledgrDigiCertAPI
  version: 0.4.0
servers:
- description: Developer Network
  url: https://digicert-api.dev.filedgr.com
security:
- bearerAuth: []
paths:
  /attachments/{data_attachment_id}:
    get:
      operationId: get_data_attachment_attachments__data_attachment_id__get
      parameters:
      - explode: false
        in: path
        name: data_attachment_id
        required: true
        schema:
          format: uuid
          title: Data Attachment Id
          type: string
        style: simple
      - explode: false
        in: header
        name: Accept
        required: false
        schema:
          enum:
          - application/vnd.com.filedgr.digicertApi.0.4.0+json
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDataAttachmentResponse'
          description: Successful Response
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemNotFoundMessage'
          description: Not Found
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Data Attachment
      tags:
      - attachments
      x-accepts: application/json
  /tokens/{token_code}/attachments:
    get:
      operationId: get_token_attachments_tokens__token_code__attachments_get
      parameters:
      - explode: false
        in: path
        name: token_code
        required: true
        schema:
          title: Token Code
          type: string
        style: simple
      - explode: true
        in: query
        name: page_size
        required: false
        schema:
          default: 10
          title: Page Size
          type: integer
        style: form
      - explode: true
        in: query
        name: page
        required: false
        schema:
          default: 1
          title: Page
          type: integer
        style: form
      - explode: false
        in: header
        name: Accept
        required: false
        schema:
          enum:
          - application/vnd.com.filedgr.digicertApi.0.4.0+json
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDataAttachmentPaginationSet'
          description: Successful Response
        "204":
          description: No Content
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Token Attachments
      tags:
      - tokens
      x-accepts: application/json
components:
  schemas:
    DataAttachmentStatus:
      enum:
      - UPLOAD_PENDING
      - REPLICATION_PENDING
      - ATTACHED
      title: DataAttachmentStatus
      type: string
    FileAttachmentStatus:
      enum:
      - UPLOAD_PENDING
      - REPLICATION_PENDING
      - ATTACHED
      title: FileAttachmentStatus
      type: string
    TokenStatus:
      enum:
      - SUBMITTED
      - CREATED
      - MINTED
      title: TokenStatus
      type: string
    Ledgers:
      title: Ledgers
      type: string
    FileDto:
      properties:
        id:
          format: uuid
          title: Id
          type: string
        filename:
          title: Filename
          type: string
        mimetype:
          title: Mimetype
          type: string
        created_at:
          format: date-time
          title: Created At
          type: string
        status:
          allOf:
          - $ref: '#/components/schemas/FileAttachmentStatus'
          default: UPLOAD_PENDING
        hash:
          $ref: '#/components/schemas/Hash'
        size:
          title: Size
          type: integer
        cid:
          $ref: '#/components/schemas/Cid'
      required:
      - created_at
      - filename
      - id
      - mimetype
      - size
      title: FileDto
    TokenDto:
      example:
        ledger: ledger
        mapping: Mapping
        asset_code: asset_code
        issuer_wallet: Issuer_Wallet
        created_at: 2000-01-23T04:56:07.000+00:00
        description: Description
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        status: null
      properties:
        id:
          format: uuid
          title: Id
          type: string
        created_at:
          format: date-time
          title: Created At
          type: string
        asset_code:
          title: Asset Code
          type: string
        description:
          $ref: '#/components/schemas/Description'
        ledger:
          title: Ledgers
          type: string
        status:
          $ref: '#/components/schemas/TokenStatus'
        issuer_wallet:
          $ref: '#/components/schemas/Issuer_Wallet'
        mapping:
          $ref: '#/components/schemas/Mapping'
      required:
      - asset_code
      - created_at
      - id
      - ledger
      - status
      title: TokenDto
    GetDataAttachmentPaginationSet:
      example:
        total_records: 0
        total_pages: 1
        current_page: 6
        content:
        - file_count: 6
          filename: filename
          token_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          size: 0
          created_at: 2000-01-23T04:56:07.000+00:00
          presigned_url: Presigned_Url
          files: ""
          tx_hash: Tx_Hash
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          upload_as_zip: false
          status: null
          token:
            ledger: ledger
            mapping: Mapping
            asset_code: asset_code
            issuer_wallet: Issuer_Wallet
            created_at: 2000-01-23T04:56:07.000+00:00
            description: Description
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            status: null
        - file_count: 6
          filename: filename
          token_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          size: 0
          created_at: 2000-01-23T04:56:07.000+00:00
          presigned_url: Presigned_Url
          files: ""
          tx_hash: Tx_Hash
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          upload_as_zip: false
          status: null
          token:
            ledger: ledger
            mapping: Mapping
            asset_code: asset_code
            issuer_wallet: Issuer_Wallet
            created_at: 2000-01-23T04:56:07.000+00:00
            description: Description
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            status: null
      properties:
        total_records:
          title: Total Records
          type: integer
        current_page:
          title: Current Page
          type: integer
        total_pages:
          title: Total Pages
          type: integer
        content:
          default: []
          items:
            $ref: '#/components/schemas/GetDataAttachmentResponse'
          type: array
      required:
      - current_page
      - total_pages
      - total_records
      title: GetDataAttachmentPaginationSet
    GetDataAttachmentResponse:
      example:
        file_count: 6
        filename: filename
        token_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        size: 0
        created_at: 2000-01-23T04:56:07.000+00:00
        presigned_url: Presigned_Url
        files: ""
        tx_hash: Tx_Hash
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        upload_as_zip: false
        status: null
        token:
          ledger: ledger
          mapping: Mapping
          asset_code: asset_code
          issuer_wallet: Issuer_Wallet
          created_at: 2000-01-23T04:56:07.000+00:00
          description: Description
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          status: null
      properties:
        id:
          format: uuid
          title: Id
          type: string
        created_at:
          format: date-time
          title: Created At
          type: string
        status:
          $ref: '#/components/schemas/DataAttachmentStatus'
        presigned_url:
          $ref: '#/components/schemas/Presigned_Url'
        token_id:
          format: uuid
          title: Token Id
          type: string
        filename:
          title: Filename
          type: string
        tx_hash:
          $ref: '#/components/schemas/Tx_Hash'
        upload_as_zip:
          default: false
          title: Upload As Zip
          type: boolean
        size:
          $ref: '#/components/schemas/Size'
        token:
          $ref: '#/components/schemas/GetDataAttachmentResponse_token'
        file_count:
          $ref: '#/components/schemas/File_Count'
        files:
          $ref: '#/components/schemas/Files'
      required:
      - created_at
      - filename
      - id
      - status
      - token_id
      title: GetDataAttachmentResponse
    HTTPValidationError:
      example:
        detail:
        - msg: msg
          loc:
          - ValidationError_loc_inner
          - ValidationError_loc_inner
          type: type
        - msg: msg
          loc:
          - ValidationError_loc_inner
          - ValidationError_loc_inner
          type: type
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
      title: HTTPValidationError
    ItemNotFoundMessage:
      example:
        error: error
        message: message
      properties:
        error:
          title: Error
          type: string
        message:
          title: Message
          type: string
      required:
      - error
      - message
      title: ItemNotFoundMessage
    ValidationError:
      example:
        msg: msg
        loc:
        - ValidationError_loc_inner
        - ValidationError_loc_inner
        type: type
      properties:
        loc:
          items:
            $ref: '#/components/schemas/ValidationError_loc_inner'
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
    Hash:
      anyOf:
      - type: string
      - nullable: true
      title: Hash
    Cid:
      anyOf:
      - type: string
      - nullable: true
      default: ""
      title: Cid
    Description:
      anyOf:
      - type: string
      - nullable: true
      title: Description
    Issuer_Wallet:
      anyOf:
      - type: string
      - nullable: true
      title: Issuer Wallet
    Mapping:
      anyOf:
      - type: string
      - nullable: true
      title: Mapping
    Presigned_Url:
      anyOf:
      - type: string
      - nullable: true
      default: ""
      title: Presigned Url
    Tx_Hash:
      anyOf:
      - type: string
      - nullable: true
      title: Tx Hash
    Size:
      anyOf:
      - type: integer
      - nullable: true
      default: 0
      title: Size
    GetDataAttachmentResponse_token:
      anyOf:
      - $ref: '#/components/schemas/TokenDto'
      - nullable: true
    File_Count:
      anyOf:
      - type: integer
      - nullable: true
      default: 0
      title: File Count
    Files:
      anyOf:
      - items:
          $ref: '#/components/schemas/FileDto'
      - nullable: true
      default: []
      title: Files
    ValidationError_loc_inner:
      anyOf:
      - type: string
      - type: integer
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      description: Every request will require a JWT Token. However for public sites
        it has the shape 'bearer public'
      scheme: bearer
      type: http

