openapi: 3.1.0
info:
  title: VR-Training backend with pockebase (admin panel)
  version: 1.0.0
servers:
- url: http://localhost:3000
paths:
  /clients/login:
    post:
      description: login using pocketbase auth with password and username
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_clients_login_post_request'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_clients_login_post_200_response'
          description: To test
      summary: client login
      x-content-type: application/json
      x-accepts: application/json
  /clients/add_device:
    get:
      description: add new device to client license using the generated code
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_clients_add_device_get_200_response'
          description: the generated code
      summary: 'add new device '
      x-accepts: application/json
  /clients/list_devices:
    get:
      description: list all devices connected to client
      responses:
        "200":
          content:
            array:
              schema:
                $ref: '#/components/schemas/_clients_list_devices_get_200_response'
          description: devices list
      summary: list devices
      x-accepts: array
  /clients/start_session:
    post:
      description: start game session so the player can start the game from device
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_clients_start_session_post_request'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_clients_login_post_200_response'
          description: To test
      summary: start game session
      x-content-type: application/json
      x-accepts: application/json
components:
  schemas:
    _clients_list_devices_get_200_response:
      properties:
        device_id:
          type: string
        device_serial_number:
          type: string
        client_id:
          type: string
        connect_code:
          type: string
        ready:
          type: boolean
        running_scenario:
          type: string
        running_record:
          type: string
    _clients_login_post_200_response:
      example:
        name: name
        seats: seats
      properties:
        name:
          type: string
        seats:
          type: string
    _clients_login_post_request:
      properties:
        username:
          type: string
        password:
          type: string
    _clients_add_device_get_200_response:
      example:
        connect_code: 0.8008281904610115
      properties:
        connect_code:
          type: number
    _clients_start_session_post_request:
      properties:
        device_id:
          type: string
        scenario_id:
          type: string
        user_id:
          type: string

