openapi: 3.1.0
info:
  description: Just one end point to check licenses.
  title: SDefender License Server
  version: 1.0.0
servers:
- url: /
paths:
  /api/v1/licenses/check:
    post:
      description: The preferable way is to use "Bearer" header to send license code
        instead of "key" parameter.
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/PostApiV1LicensesCheckRequestBody'
      responses:
        "401":
          description: Authentication is invalid
        "403":
          description: License is invalid
        "204":
          description: License is valid (no response body)
      summary: Check License
      x-content-type: application/json;charset=UTF-8
      x-accepts: application/json
components:
  schemas:
    PostApiV1LicensesCheckRequestBody:
      example:
        process: 6.027456183070403
        address: address
        devices: 0.8008281904610115
        key: key
      properties:
        key:
          type: string
        address:
          type: string
        devices:
          type: number
        process:
          type: number
      required:
      - address
      - devices
      - key
      - process

