openapi: 3.1.0
info:
  description: API for updating member course completion
  title: BBE Nexus LMS API
  version: "1"
servers:
- url: /
paths:
  /course/update/{memberId}:
    post:
      description: Endpoint to update a member with course completion
      operationId: memberCourseUpdate
      parameters:
      - description: API key for authorization
        explode: false
        in: header
        name: x-api-key
        required: true
        schema:
          type: string
        style: simple
      - description: API client ID
        explode: false
        in: header
        name: x-client-id
        required: true
        schema:
          type: string
        style: simple
      - description: Member ID to update
        explode: false
        in: path
        name: memberId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/memberCourseUpdate_request'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/memberCourseUpdate_200_response'
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/memberCourseUpdate_400_response'
          description: Bad request
      summary: Endpoint to update a member with course completion
      tags:
      - Update Member Course
      x-content-type: application/json
      x-accepts: application/json
components:
  schemas:
    MemberCourseUpdateRequest:
      example:
        qualificationType: qualificationType
        qualificationLevel: qualificationLevel
        courseCode: courseCode
        qualificationDate: 2000-01-23
        status: status
      properties:
        courseCode:
          description: ID of the course completed by the member
          type: string
        qualificationType:
          description: Type of qualification completed
          type: string
        qualificationLevel:
          description: Level of qualification
          type: string
        status:
          description: Completed status of course
          type: string
        qualificationDate:
          description: Date when the course was completed
          format: date
          type: string
      required:
      - courseCode
      - qualificationDate
      - qualificationLevel
      - qualificationType
      - status
    MemberCourseUpdateResponse:
      properties:
        statusCode:
          type: ""
        message:
          description: Confirmation message for successful course update
          type: string
    Error:
      properties:
        message:
          description: Error message
          type: string
    memberCourseUpdate_request:
      properties:
        courseCode:
          description: ID of the course completed by the member
          type: string
        qualificationType:
          description: Type of qualification completed
          type: string
        qualificationLevel:
          description: Level of qualification
          type: string
        status:
          description: Completed status of course
          type: string
        qualificationDate:
          description: Date when the course was completed
          format: date
          type: string
      required:
      - courseCode
      - qualificationDate
      - qualificationLevel
      - qualificationType
      - status
    memberCourseUpdate_200_response:
      example:
        message: message
        statusCode: ""
      properties:
        statusCode:
          type: ""
        message:
          description: Confirmation message for successful course update
          type: string
    memberCourseUpdate_400_response:
      example:
        message: message
      properties:
        message:
          description: Error message
          type: string

