openapi: 3.1.0
info:
  description: Retrieves customer data
  title: get_customer_object
  version: v1.0.0
servers:
- url: https://openaiagent.gottacatchemall.repl.co
paths:
  /get_user_id:
    post:
      deprecated: false
      description: Get customer data given user email
      operationId: GetCustomerDataByEmail
      parameters:
      - description: The email of the customer to get data about
        explode: true
        in: query
        name: email
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CustomerObject'
                type: object
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      x-accepts: application/json
components:
  schemas:
    CustomerObject:
      properties:
        Customer ID:
          type: number
        First Name:
          type: string
        Last Name:
          type: string
        Email:
          type: string
        Accepts Email Marketing:
          type: string
        Company:
          nullable: true
          type: string
        Address1:
          type: string
        Address2:
          nullable: true
          type: string
        City:
          type: string
        Province:
          type: string
        Province Code:
          type: string
        Country:
          type: string
        Country Code:
          type: string
        Zip:
          type: string
        Phone:
          type: string
        Accepts SMS Marketing:
          type: string
        Total Spent:
          type: number
        Total Orders:
          type: integer
        Tags:
          items:
            description: TODO default missing array inner type to string
            type: string
          type: array
        Note:
          nullable: true
          type: string
        Tax Exempt:
          type: string

