openapi: 3.0.1
info:
  description: "API для работы с учениками, занятиями и оценками"
  title: Тестовое задание
  version: 1.0.0
servers:
- url: /api
paths:
  /users:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/User'
                type: array
          description: Успешный запрос
      summary: Получить список учеников
      x-accepts: application/json
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        description: Данные нового ученика
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: Успешное добавление
      summary: Добавить одного ученика
      x-codegen-request-body-name: user
      x-content-type: application/json
      x-accepts: application/json
  /lessons/{id}:
    get:
      parameters:
      - description: ID занятия
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lesson'
          description: Успешный запрос
      summary: Получить информацию о занятии по ID
      x-accepts: application/json
  /lessons:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lesson'
        description: Данные нового занятия
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lesson'
          description: Успешное добавление
      summary: Добавить занятие
      x-codegen-request-body-name: lesson
      x-content-type: application/json
      x-accepts: application/json
  /lessons/{id}/evaluations:
    post:
      parameters:
      - description: ID занятия
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Evaluation'
        description: Данные новой оценки
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Evaluation'
          description: Успешное добавление
      summary: Добавить оценку ученика по занятию
      x-codegen-request-body-name: evaluation
      x-content-type: application/json
      x-accepts: application/json
components:
  schemas:
    User:
      example:
        name: name
        id: 0
        age: 6
      properties:
        id:
          type: integer
        name:
          type: string
        age:
          type: integer
      type: object
    Lesson:
      example:
        date: 2000-01-23T04:56:07.000+00:00
        subject: subject
        id: 0
      properties:
        id:
          type: integer
        subject:
          type: string
        date:
          format: date-time
          type: string
      type: object
    Evaluation:
      example:
        grade: 3
        lessonId: 1
        id: 0.8008281904610115
        userId: 6
      properties:
        id:
          type: number
        userId:
          type: integer
        lessonId:
          type: integer
        grade:
          maximum: 5
          minimum: 1
          type: integer
      type: object
x-original-swagger-version: "2.0"

