openapi: 3.1.0
info:
  description: "## Base URL\n\nThe base URL for all API requests is:\n\n`http://104.42.44.252/BoomAPI/api/Genric`\n\
    \n## Errors\n\nThis API uses the following error codes:\n\n- `100 Success`\n-\
    \ `101 User Request Error`\n- `102 Error` \n------"
  title: Boom API
  version: 1.0.0
servers:
- url: http://104.42.44.252/BoomAPI/api/Genric
paths:
  /BoomInstantActivation:
    post:
      description: |-
        <h1>Description</h1> <h3>The "Activate Mdn with eSim / physical sim" API activates new number for a customer using eSim or physical sim. The new number can be activated only after a  successful validation which checks if the IMEI is valid and compatible to eSim technology or not.<h3>
        <h1>Endpoints</h1> <h4>/BoomInstantActivation</h4>
        <h1>Request Type</h1> <h4>Post</h4>
        <h2>Parameters</h2> <ul> <li><strong>ClientCode</strong> (String - Mandatory)</li> <li><strong>IMEI</strong> (String - Mandatory) IMEI length Can't be greater than 16 and less than 14.</li> <li><strong>SerialNumber</strong> (String - with eSim mandatory otherwise optional) Serial No. Can't be greater than 23 or less than 18.</li> <li><strong>PortMobileNo</strong> (String - for portin mandatory otherwise optional)</li> <li><strong>Carrrier_Type</strong> (Int - Mandatory) 97 for purple2 and 90 for red.</li> <li><strong>TariffId</strong> (Int - Mandatory)</li> <li><strong>Month</strong> (Int - Mandatory)</li> <li><strong>Rental</strong> (decimal - Mandatory)</li> <li><strong>isWifi</strong> (bool - Mandatory) True- with Wi-Fi and False- without Wi-Fi.</li> <li><strong>TransactionId</strong> (String - Mandatory) Starting from “BRI” for instant activation.</li> <li><strong>ActivationOrPortin</strong> (Int - Mandatory) 0 for Activation and 1 for Portin.</li> <li><strong>Customer_Details</strong> (Object - Mandatory) <ul> <li><strong>Firstname</strong> (String - Mandatory)</li> <li><strong>LastName</strong> (String - Mandatory)</li> <li><strong>Email</strong> (String - Optional)</li> <li><strong>Address</strong> (String - Mandatory)</li> <li><strong>City</strong> (String - Mandatory)</li> <li><strong>State</strong> (String - Mandatory)</li> <li><strong>Zip</strong> (String - Mandatory)</li> <li><strong>contactNumber</strong> (String - for portin mandatory otherwise optional) Port contact no can only be 10 digits.</li> </ul> </li> </ul>
      operationId: add Mdn
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InstantActivationRequest'
        description: Add Activation
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: Successful
      tags:
      - Instant Activation
      x-content-type: application/json
      x-accepts: application/json
  /BoomRecharge:
    post:
      description: |-
        <h1>Description</h1> <h3>The "Recharge by Mdn" API is a specific type of recharge API that allows users to recharge their mobile phone using their Mdn.<h3>
        <h1>Endpoints</h1> <h4>/BoomRecharge</h4>
        <h1>Request Type</h1> <h4>Post</h4>
        <h3>Parameters</h3> <ul> <li><code>ClientCode</code> (String - Mandatory)</li> <li><code>TransactionId</code> (String - Mandatory) Starting with "BRI" for instant activation.</li> <li><code>MSISDN</code> (String - Mandatory) MSISDN must be exactly 10 digits.</li> <li><code>PlanID</code> (String - Mandatory)</li> <li><code>Rental</code> (Decimal - Mandatory)</li> <li><code>Carrier_Type</code> (Int - Mandatory) 97 for purple2 and 90 for red.</li> <li><code>RechargeType</code> (Int - Mandatory) 0 for after plan expires and 1 for starting from.</li> </ul>
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RechargeRequest'
        description: Add Recharge
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: successful
      tags:
      - Recharge
      x-content-type: application/json
      x-accepts: application/json
  /BoomCheckPortinMdn:
    post:
      description: |-
        <h1>Description</h1> <h3>The "Check Port in by Mdn" API check if IMEI, SIM and MDN are compatible. We get status which describes if the MDN is Portable. This API is called during the port in number flow to check port possibility. <h3>
        <h1>Endpoints</h1> <h4>/BoomCheckPortinMdn</h4>
        <h1>Request Type</h1> <h4>Post</h4>
        <h3>Parameters</h3> <ul> <li><strong>ClientCode</strong> (String - Mandatory)</li> <li><strong>IMEI</strong> (String - Mandatory) IMEI length must be between 14 and 16 characters.</li> <li><strong>SerialNumber</strong> (String - with eSIM mandatory, otherwise optional) Serial No. must be between 18 and 23 characters.</li> <li><strong>Msisdn</strong> (String - Mandatory) MSISDN must be exactly 10 digits.</li> <li><strong>is4g</strong> (Boolean - for portin mandatory, otherwise optional) True with 4G and False without 4G.</li> </ul>
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckPortinMdnRequest'
        description: Check Portin by Mdn
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: successful
      tags:
      - Check Portin Mdn
      x-content-type: application/json
      x-accepts: application/json
  /BoomGetMdnStatus:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetDetailsByMdnRequest'
        description: |-
          <h1>Description</h1> <h3>The "Get Details By Mdn" Api displays information about Mdn’s details, subscription details, customer details and plan. <h3>
          <h1>Endpoints</h1> <h4>/BoomGetMdnStatus</h4>
          <h1>Request Type</h1> <h4>Post</h4>
          <h3>Parameters</h3> <ul> <li><strong>ClientCode</strong> (String - Mandatory)</li> <li><strong>Msisdn</strong> (String - Mandatory) MSISDN must be exactly 10 digits.</li> <li><strong>Carrier_Type</strong> (Int - Mandatory) 97 for purple2 and 90 for red.</li> </ul>
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: successful
      tags:
      - Get Details By Mdn
      x-content-type: application/json
      x-accepts: application/json
  /BoomCheckPortinStatus:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckPortinStatusRequest'
        description: |-
          <h1>Description</h1> <h3>The "Check Port-in Status by Mdn" API allows users to inquire about the port-in status of a mobile number (Mdn) when transferring their phone number from one telecommunication service provider to another. Porting, or number portability, enables users to keep their existing phone number when switching to a new provider. <h3>
          <h1>Endpoints</h1> <h4>/BoomCheckPortinStatus</h4>
          <h1>Request Type</h1> <h4>Post</h4>
          <h3>Parameters</h3> <ul> <li><strong>ClientCode</strong> (String - Mandatory)</li> <li><strong>Msisdn</strong> (String - Mandatory) MSISDN must be exactly 10 digits.</li> <li><strong>Carrier_Type</strong> (Int - Mandatory) 97 for purple2 and 90 for red.</li> </ul>
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: successful
      tags:
      - Check Portin Status
      x-content-type: application/json
      x-accepts: application/json
  /BoomCheckIMEI:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckIMEIRequest'
        description: |-
          <h1>Description</h1> <h3>The "Check by IMEI" API designed to provide information about the validity and status of an International Mobile Equipment Identity (IMEI) number. IMEI validity can refer to various aspects such as whether the device associated with the IMEI is legitimate. <h3>
          <h1>Endpoints</h1> <h4>/BoomCheckImei</h4>
          <h1>Request Type</h1> <h4>Post</h4>
          <h3>Parameters</h3> <ul> <li><strong>ClientCode</strong> (String - Mandatory)</li> <li><strong>IMEI</strong> (String - Mandatory) IMEI length must be between 14 and 16 characters.</li> <li><strong>Carrier_Type</strong> (Int - Mandatory) 97 for purple2 and 90 for red.</li> <li><strong>is4g</strong> (Boolean - Mandatory) True with 4G and False without 4G.</li> </ul>
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: successful
      tags:
      - Check IMEI
      x-content-type: application/json
      x-accepts: application/json
  /BoomCheckSerialNumber:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckSerialNumberRequest'
        description: |-
          <h1>Description</h1> <h3>The "Check by Serial Number" API designed to provide information about the validity of a SIM card based on its serial number. SIM card validity can refer to various aspects such as whether the SIM card is active. <h3>
          <h1>Endpoints</h1> <h4>/BoomCheckSerialNumber</h4>
          <h1>Request Type</h1> <h4>Post</h4>
          <h3>Parameters</h3> <ul> <li><strong>ClientCode</strong> (String - Mandatory)</li> <li><strong>SerialNumber</strong> (String - Mandatory) Serial No. must be between 18 and 23 characters.</li> <li><strong>Carrier_Type</strong> (Int - Mandatory) 97 for purple2 and 90 for red.</li> </ul>
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: successful
      tags:
      - Check Serial Number
      x-content-type: application/json
      x-accepts: application/json
components:
  schemas:
    Customer_Details:
      example:
        zip: "01011"
        firstName: TestDemoCustomer
        lastName: TestDemoCustomer
        portableFromAccountPassCode: "01011"
        address: 21 Main St
        city: Chester
        contactNumber: "9988776655"
        portableFromAccountNumber: "554433223333"
        state: MA
        email: testdemo@customer.com
        portableFromProvider: test
      properties:
        firstName:
          example: TestDemoCustomer
          format: ""
          type: string
        lastName:
          example: TestDemoCustomer
          type: string
        email:
          example: testdemo@customer.com
          format: ""
          type: string
        address:
          example: 21 Main St
          type: string
        city:
          example: Chester
          format: ""
          type: string
        state:
          example: MA
          type: string
        zip:
          example: "01011"
          format: ""
          type: string
        contactNumber:
          example: "9988776655"
          type: string
        portableFromProvider:
          example: test
          type: string
        portableFromAccountNumber:
          example: "554433223333"
          format: ""
          type: string
        portableFromAccountPassCode:
          example: "01011"
          type: string
      xml:
        name: Customer_Details
    InstantActivationRequest:
      example:
        TariffId: "1"
        PortMobileNo: xx
        ActivationOrPortin: 0
        IMEI: xx
        Carrrier_Type: 97
        TransactionId: xx
        Month: 1
        Customer_Details:
          zip: "01011"
          firstName: TestDemoCustomer
          lastName: TestDemoCustomer
          portableFromAccountPassCode: "01011"
          address: 21 Main St
          city: Chester
          contactNumber: "9988776655"
          portableFromAccountNumber: "554433223333"
          state: MA
          email: testdemo@customer.com
          portableFromProvider: test
        SerialNumber: xx
        Rental: 3
        isWifi: false
        ClientCode: xx
        isEsim: false
      properties:
        ClientCode:
          example: xx
          type: string
        IMEI:
          example: xx
          type: string
        SerialNumber:
          example: xx
          type: string
        PortMobileNo:
          example: xx
          type: string
        Carrrier_Type:
          example: 97
          type: integer
        TariffId:
          example: "1"
          type: string
        Month:
          example: 1
          type: integer
        Rental:
          example: 3
          type: integer
        isWifi:
          example: false
          type: boolean
        isEsim:
          example: false
          type: boolean
        TransactionId:
          example: xx
          type: integer
        ActivationOrPortin:
          example: 0
          type: integer
        Customer_Details:
          $ref: '#/components/schemas/Customer_Details'
      xml:
        name: pet
    RechargeRequest:
      example:
        MSISDN: "9999988888"
        Rental: 3
        PlanID: "1"
        ClientCode: xx
        RechargeType: 0
        Carrier_Type: 90
        TransactionId: xx
      properties:
        ClientCode:
          example: xx
          type: string
        TransactionId:
          example: xx
          type: string
        MSISDN:
          example: "9999988888"
          type: string
        PlanID:
          example: "1"
          type: string
        Rental:
          example: 3
          type: number
        Carrier_Type:
          example: 90
          type: integer
        RechargeType:
          example: 0
          type: integer
      xml:
        name: pet
    CheckPortinMdnRequest:
      example:
        Msisdn: xx
        SerialNumber: xx
        ClientCode: xx
        Imei: xx
        Carrier_Type: 90
      properties:
        ClientCode:
          example: xx
          type: string
        Imei:
          example: xx
          type: string
        SerialNumber:
          example: xx
          type: string
        Msisdn:
          example: xx
          type: string
        Carrier_Type:
          example: 90
          type: integer
      xml:
        name: pet
    GetDetailsByMdnRequest:
      example:
        Msisdn: xx
        ClientCode: xx
        Carrier_Type: 90
      properties:
        ClientCode:
          example: xx
          type: string
        Msisdn:
          example: xx
          type: string
        Carrier_Type:
          example: 90
          type: integer
      xml:
        name: pet
    CheckPortinStatusRequest:
      example:
        Msisdn: xxx
        ClientCode: xx
        Carrier_Type: 90
      properties:
        ClientCode:
          example: xx
          type: string
        Msisdn:
          example: xxx
          type: string
        Carrier_Type:
          example: 90
          type: integer
      xml:
        name: pet
    CheckIMEIRequest:
      example:
        ClientCode: xx
        Imei: xx
        is4g: false
        Carrier_Type: 90
      properties:
        ClientCode:
          example: xx
          type: string
        Imei:
          example: xx
          type: string
        Carrier_Type:
          example: 90
          type: integer
        is4g:
          example: false
          type: boolean
      xml:
        name: pet
    CheckSerialNumberRequest:
      example:
        SerialNumber: xxx
        ClientCode: xxx
        Carrier_Type: 90
      properties:
        ClientCode:
          example: xxx
          type: string
        SerialNumber:
          example: xxx
          type: string
        Carrier_Type:
          example: 90
          type: integer
      xml:
        name: pet
    ApiResponse:
      example:
        data: data
        details: string
        errorcode: 101
        status: true
      properties:
        errorcode:
          example: 101
          format: ""
          type: string
        data:
          type: string
          example: null
        details:
          example: string
          type: string
        status:
          type: boolean
      xml:
        name: '##default'
    GetDetailsByMdnApiResponse:
      properties:
        errorcode:
          example: 101
          format: ""
          type: string
        data:
          type: string
          example: null
        details:
          example: string
          type: string
        creationTime:
          type: string
          example: null
        delayActivation:
          example: false
          type: boolean
        status:
          type: boolean
      xml:
        name: '##default2'

