openapi: 3.0.0
info:
  contact:
    email: itm.km23@muenchen.de
  description: kita finder+ - K@rl Schnittstellenspezifikation für die Übertragung
    von  Ereignissen aus dem Antragsmodul
  title: kf+ - K@rl Schnittstellenspezifikation
  version: "11"
servers:
- url: /
security:
- ApiKeyAuth: []
paths:
  /api/kitafinder/antraege/fristablauf:
    post:
      description: Fristablauf (E1) Nur für Neuverträge wenn 4 Wochen nach Neuvertrag
        kein Antrag gestellt wurde
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_api_kitafinder_antraege_fristablauf_post_request'
      responses:
        "200":
          description: Fristablauf übertragen
        "401":
          description: API key nicht angegeben oder ungültig
          headers:
            WWW_Authenticate:
              explode: false
              schema:
                type: string
              style: simple
        "4XX":
          description: Sonstiger Client Fehler (4xx)
        "5XX":
          description: Server Fehler (5xx)
      summary: Fristablauf (E1)
      tags:
      - Anträge
      x-content-type: application/json
      x-accepts: application/json
  /api/kitafinder/antraege/regelsatz:
    post:
      description: Neuen Antrag auf Regelsatz erstellen (E2)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_api_kitafinder_antraege_regelsatz_post_request'
      responses:
        "201":
          description: Create (E2) Antrag auf Regelsatz
        "401":
          description: API key nicht angegeben oder ungültig
          headers:
            WWW_Authenticate:
              explode: false
              schema:
                type: string
              style: simple
        "4XX":
          description: Sonstiger Client Fehler (4xx)
        "5XX":
          description: Server Fehler (5xx)
      summary: Neuen Antrag auf Regelsatz erstellen (E2)
      tags:
      - Anträge
      x-content-type: application/json
      x-accepts: application/json
  /api/kitafinder/antraege/ermaessigungselbsteinschaetzung:
    post:
      description: Neuen Antrag auf Ermäßigung mit Selbsteinschätzung erstellen (E3)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_api_kitafinder_antraege_ermaessigungselbsteinschaetzung_post_request'
      responses:
        "201":
          description: Create (E3) Antrag auf Ermäßigung mit Selbsteinschätzung
        "401":
          description: API key nicht angegeben oder ungültig
          headers:
            WWW_Authenticate:
              explode: false
              schema:
                type: string
              style: simple
        "4XX":
          description: Sonstiger Client Fehler (4xx)
        "5XX":
          description: Server Fehler (5xx)
      summary: Neuen Antrag auf Ermäßigung mit Selbsteinschätzung erstellen (E3)
      tags:
      - Anträge
      x-content-type: application/json
      x-accepts: application/json
  /api/kitafinder/antraege/ermaessigungmitbelegen:
    post:
      description: Neuen Antrag auf Ermäßigung mit Belegen erstellen (E4)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_api_kitafinder_antraege_ermaessigungmitbelegen_post_request'
      responses:
        "201":
          description: Create (E4) Antrag auf Ermäßigung mit Belegen
        "401":
          description: API key nicht angegeben oder ungültig
          headers:
            WWW_Authenticate:
              explode: false
              schema:
                type: string
              style: simple
        "4XX":
          description: Sonstiger Client Fehler (4xx)
        "5XX":
          description: Server Fehler (5xx)
      summary: Neuen Antrag auf Ermäßigung mit Belegen erstellen (E4)
      tags:
      - Anträge
      x-content-type: application/json
      x-accepts: application/json
  /api/kitafinder/antraege/unterlageneingang:
    post:
      description: Unterlageneingang (E5)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_api_kitafinder_antraege_unterlageneingang_post_request'
      responses:
        "200":
          description: Update (E5) Unterlageneingang
        "401":
          description: API key nicht angegeben oder ungültig
          headers:
            WWW_Authenticate:
              explode: false
              schema:
                type: string
              style: simple
        "4XX":
          description: Sonstiger Client Fehler (4xx)
        "5XX":
          description: Server Fehler (5xx)
      summary: Unterlageneingang (E5)
      tags:
      - Anträge
      x-content-type: application/json
      x-accepts: application/json
  /api/kitafinder/antraege/unterlagenfristgesetzt:
    post:
      description: Frist für Unterlagen wurde gesetzt (E6)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_api_kitafinder_antraege_unterlagenfristgesetzt_post_request'
      responses:
        "200":
          description: Update (E6) Frist für Unterlagen wurde gesetzt
        "401":
          description: API key nicht angegeben oder ungültig
          headers:
            WWW_Authenticate:
              explode: false
              schema:
                type: string
              style: simple
        "4XX":
          description: Sonstiger Client Fehler (4xx)
        "5XX":
          description: Server Fehler (5xx)
      summary: Frist für Unterlagen wurde gesetzt (E6)
      tags:
      - Anträge
      x-content-type: application/json
      x-accepts: application/json
components:
  responses:
    UnauthorizedError:
      description: API key nicht angegeben oder ungültig
      headers:
        WWW_Authenticate:
          explode: false
          schema:
            type: string
          style: simple
    ClientError:
      description: Sonstiger Client Fehler (4xx)
    ServerError:
      description: Server Fehler (5xx)
  schemas:
    AntragGemeinsamePflichtfelder:
      required:
      - einrichtungsjahr
      - geburtsdatum
      - id
      - kf_kind_id
      - kf_kita_id
      - kita_kibig_id
      - nachname
      - timestamp
      - vorname
      type: object
    AntragKopfdaten:
      properties:
        id:
          description: Eindeutige ID des Events
          example: 123457
          type: integer
        timestamp:
          description: Zeitstempel des Events (ISO 8601)
          example: 2018-03-20T09:12:28Z
          format: date-time
          type: string
        kf_kind_id:
          description: "eindeutige ID für das Kind, KindmappenID aus Kita-Planer"
          type: integer
        nachname:
          example: Müller
          maxLength: 255
          minLength: 1
          type: string
        vorname:
          example: Maximilian
          maxLength: 255
          minLength: 1
          type: string
        geburtsdatum:
          description: Geburstdatum des Kindes
          example: 15.04.2018
          format: TT.MM.JJJJ
          pattern: "^\\d{2}\\.\\d{2}\\.\\d{4}$"
          type: string
        kf_kita_id:
          description: Einrichtungs-ID aus Kita-Planer
          type: integer
        kind_kibig_id:
          description: KiBiG-ID des Kindes
          type: string
        kita_kibig_id:
          description: KiBiG-ID der Einrichtung
          type: string
        einrichtungsjahr:
          description: "erste Jahreszahl des Kitajahre, z.B. 2021 bei 2021/2022"
          example: "2021"
          format: JJJJ
          pattern: "^\\d{4}$"
          type: string
        antragsdatum:
          description: Datum der Antragsstellung
          example: 13.08.2022
          format: TT.MM.JJJJ
          pattern: "^\\d{2}\\.\\d{2}\\.\\d{4}$"
          type: string
        antragsnummer:
          type: integer
      type: object
    Fristablauf:
      properties:
        zeitraum_von:
          description: Vertragsbeginn
          example: 01.09.2021
          format: TT.MM.JJJJ
          pattern: "^\\d{2}\\.\\d{2}\\.\\d{4}$"
          type: string
      required:
      - kind_kibig_id
      - kita_kibig_id
      - zeitraum_von
      type: object
    AntragRegelsatz:
      properties:
        zeitraum_von:
          description: Vertragsbeginn
          example: 01.09.2021
          format: TT.MM.JJJJ
          pattern: "^\\d{2}\\.\\d{2}\\.\\d{4}$"
          type: string
      required:
      - zeitraum_von
      type: object
    AntragErmSelbsteinschaetzung:
      properties:
        zeitraum_von:
          description: Vertragsbeginn
          example: 01.09.2021
          format: TT.MM.JJJJ
          pattern: "^\\d{2}\\.\\d{2}\\.\\d{4}$"
          type: string
        einkommenInCent:
          description: Falls im Antrag Ermäßigung nach Einkommen beantragt wurde
          type: integer
        einkommensjahr:
          description: Kalendervorvorjahr
          example: "2021"
          format: JJJJ
          pattern: "^\\d{4}$"
          type: string
        bezugSozialleistungen:
          description: "false - kein Bezug / keine Angabe, true - Bezug Sozialleistungen"
          example: false
          type: boolean
        anzahlAeltererGeschwisterkinder:
          description: Falls im Antrag Geschwisterkindermäßigung beantragt wurde
          example: 2
          type: integer
      required:
      - zeitraum_von
      type: object
    AntragErmMitBelegen:
      properties:
        zeitraum_von:
          description: "Wenn Standardantrag oder Folgeantrag, dann 1.9. des aktuellen\
            \ Einrichungsjahres Datumseingabe der Eltern"
          example: 01.09.2021
          format: TT.MM.JJJJ
          pattern: "^\\d{2}\\.\\d{2}\\.\\d{4}$"
          type: string
        berechnungsart_besuch:
          description: Arten der Berechnung der Besuchsgebühren. Werden von K@RL definiert
            und müssen im Antragsmodul konfigurierbar hinterlegt werden können.
          example: Nur Einkommen des Kalendervorvorjahres
          type: string
        berechnungsart_verpflegung:
          description: Arten der Berechnung der Verpflegungsgebühren. Werden von K@RL
            definiert und müssen im Antragsmodul konfigurierbar hinterlegt werden
            können.
          example: volle Verpflegungsgebühr
          type: string
        einkommenInCent:
          description: "Einkommenshöhe, anhand dessen die Gebührenhöhe in K@RL berechnet\
            \ wird."
          type: integer
        einkommensjahr:
          description: "vom SB je nach Antragsart, bei Ermäßigung aufgrund des Einkommens\
            \ das Kalendervorvorjahr, bei Sozialleistungen das aktuelle Einrichtungsjahr"
          example: "2021"
          format: JJJJ
          pattern: "^\\d{4}$"
          type: string
        unterlagenstatus:
          $ref: '#/components/schemas/Unterlagenstatus'
        bemerkung:
          type: string
        kennzeichen_individuelle_festsetzung:
          description: "false - automatisch, true - individuelle Festsetzung durch\
            \ SB in K@RL"
          example: false
          type: boolean
        geschwisterkinder:
          description: Pflicht bei Antrag auf Geschwisterermäßigung
          items:
            $ref: '#/components/schemas/AntragErmMitBelegen_geschwisterkinder_inner'
          type: array
      required:
      - kennzeichen_individuelle_festsetzung
      - unterlagenstatus
      - zeitraum_von
      type: object
    AntragUnterlagenEingang:
      type: object
    AntragUnterlagenfristGesetzt:
      properties:
        wiedervorlagedatum:
          example: 15.04.2018
          format: TT.MM.JJJJ
          pattern: "^\\d{2}\\.\\d{2}\\.\\d{4}$"
          type: string
        bemerkung:
          type: string
      required:
      - wiedervorlagedatum
      type: object
    Unterlagenstatus:
      description: Unterlagenstatus
      enum:
      - OHNE
      - ANGEFORDERT
      - EINGEGANGEN_NICHT_GEPRUEFT
      - VOLLSTAENDIG
      type: string
    BerechnungsartBesuch:
      description: Arten der Berechnung der Besuchsgebühren. Werden von K@RL definiert
        und müssen im Antragsmodul konfigurierbar hinterlegt werden können.
      example: Nur Einkommen des Kalendervorvorjahres
      type: string
    BerechnungsartVerpflegung:
      description: Arten der Berechnung der Verpflegungsgebühren. Werden von K@RL
        definiert und müssen im Antragsmodul konfigurierbar hinterlegt werden können.
      example: volle Verpflegungsgebühr
      type: string
    _api_kitafinder_antraege_fristablauf_post_request:
      allOf:
      - $ref: '#/components/schemas/AntragGemeinsamePflichtfelder'
      - $ref: '#/components/schemas/AntragKopfdaten'
      - $ref: '#/components/schemas/Fristablauf'
      required:
      - einrichtungsjahr
      - geburtsdatum
      - id
      - kf_kind_id
      - kf_kita_id
      - kita_kibig_id
      - nachname
      - timestamp
      - vorname
      - zeitraum_von
    _api_kitafinder_antraege_regelsatz_post_request:
      allOf:
      - $ref: '#/components/schemas/AntragGemeinsamePflichtfelder'
      - $ref: '#/components/schemas/AntragKopfdaten'
      - $ref: '#/components/schemas/AntragRegelsatz'
      required:
      - antragsdatum
      - antragsnummer
      - einrichtungsjahr
      - geburtsdatum
      - id
      - kf_kind_id
      - kf_kita_id
      - kita_kibig_id
      - nachname
      - timestamp
      - vorname
      - zeitraum_von
    _api_kitafinder_antraege_ermaessigungselbsteinschaetzung_post_request:
      allOf:
      - $ref: '#/components/schemas/AntragGemeinsamePflichtfelder'
      - $ref: '#/components/schemas/AntragKopfdaten'
      - $ref: '#/components/schemas/AntragErmSelbsteinschaetzung'
      required:
      - antragsdatum
      - antragsnummer
      - einrichtungsjahr
      - geburtsdatum
      - id
      - kf_kind_id
      - kf_kita_id
      - kita_kibig_id
      - nachname
      - timestamp
      - vorname
      - zeitraum_von
    _api_kitafinder_antraege_ermaessigungmitbelegen_post_request:
      allOf:
      - $ref: '#/components/schemas/AntragGemeinsamePflichtfelder'
      - $ref: '#/components/schemas/AntragKopfdaten'
      - $ref: '#/components/schemas/AntragErmMitBelegen'
      required:
      - antragsdatum
      - antragsnummer
      - einrichtungsjahr
      - geburtsdatum
      - id
      - kennzeichen_individuelle_festsetzung
      - kf_kind_id
      - kf_kita_id
      - kita_kibig_id
      - nachname
      - timestamp
      - unterlagenstatus
      - vorname
      - zeitraum_von
    _api_kitafinder_antraege_unterlageneingang_post_request:
      allOf:
      - $ref: '#/components/schemas/AntragGemeinsamePflichtfelder'
      - $ref: '#/components/schemas/AntragKopfdaten'
      - $ref: '#/components/schemas/AntragUnterlagenEingang'
      required:
      - antragsdatum
      - antragsnummer
      - einrichtungsjahr
      - geburtsdatum
      - id
      - kf_kind_id
      - kf_kita_id
      - kita_kibig_id
      - nachname
      - timestamp
      - vorname
    _api_kitafinder_antraege_unterlagenfristgesetzt_post_request:
      allOf:
      - $ref: '#/components/schemas/AntragGemeinsamePflichtfelder'
      - $ref: '#/components/schemas/AntragKopfdaten'
      - $ref: '#/components/schemas/AntragUnterlagenfristGesetzt'
      required:
      - antragsdatum
      - antragsnummer
      - einrichtungsjahr
      - geburtsdatum
      - id
      - kf_kind_id
      - kf_kita_id
      - kita_kibig_id
      - nachname
      - timestamp
      - vorname
      - wiedervorlagedatum
    AntragErmMitBelegen_geschwisterkinder_inner:
      properties:
        nachname:
          description: Pflicht bei Antrag auf Geschwisterermäßigung
          example: Müller
          maxLength: 255
          minLength: 1
          type: string
        vorname:
          description: Pflicht bei Antrag auf Geschwisterermäßigung
          example: Maximilian
          maxLength: 255
          minLength: 1
          type: string
        geburtsdatum:
          description: Pflicht bei Antrag auf Geschwisterermäßigung
          example: 15.04.2018
          format: TT.MM.JJJJ
          pattern: "^\\d{2}\\.\\d{2}\\.\\d{4}$"
          type: string
        wohnt_im_selben_haushalt:
          description: "Pflicht bei Antrag auf Geschwisterermäßigung true - Kind wohnt\
            \ im selben HH, false wohnt nicht im selben HH"
          example: true
          type: boolean
        kindergeldberechtigte:
          description: "Pflicht bei Antrag auf Geschwisterermäßigung ggf. noch zu\
            \ klären,  Namen der Personen die Kindergeldberechtigt sind"
          example: "Maria Müller, Peter Müller"
          type: string
        kind_anerkannt:
          description: Pflicht bei Antrag auf Geschwisterermäßigung true - anerkannt
            false - nicht anerkannt
          example: true
          type: boolean
      type: object
  securitySchemes:
    ApiKeyAuth:
      description: API Key um Requests zu authorisieren
      in: header
      name: X-API-KEY
      type: apiKey

