openapi: 3.1.0
info:
  contact:
    email: arpan@hackclub.com
    name: Arpan Pandey
  description: An API for Jams services and an API gateway for other needed services.
  title: JAMS API
  version: 0.0.1
servers:
- url: /
paths:
  /:
    get:
      operationId: root__get
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Root
      x-accepts: application/json
  /openai/models:
    get:
      description: Get the list of models available on OpenAI API
      operationId: models_openai_models_get
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
      security:
      - HTTPBearer: []
      summary: Models
      x-accepts: application/json
  /openai/models/{model_name}:
    get:
      description: Get the details of a model available on OpenAI API
      operationId: model_openai_models__model_name__get
      parameters:
      - explode: false
        in: path
        name: model_name
        required: true
        schema:
          title: Model Name
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      security:
      - HTTPBearer: []
      summary: Model
      x-accepts: application/json
  /openai/chat/completions:
    post:
      description: Post a chat to OpenAI API
      operationId: post_chat_completions_openai_chat_completions_post
      requestBody:
        content:
          application/json:
            schema:
              title: Data
              type: object
        required: true
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      security:
      - HTTPBearer: []
      summary: Post Chat Completions
      x-content-type: application/json
      x-accepts: application/json
  /openai/images/generations:
    post:
      description: Create an image on OpenAI API
      operationId: create_image_openai_images_generations_post
      requestBody:
        content:
          application/json:
            schema:
              title: Data
              type: object
        required: true
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      security:
      - HTTPBearer: []
      summary: Create Image
      x-content-type: application/json
      x-accepts: application/json
  /openai/embeddings:
    post:
      description: Get the embeddings of a text on OpenAI API
      operationId: embeddings_openai_embeddings_post
      requestBody:
        content:
          application/json:
            schema:
              title: Data
              type: object
        required: true
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      security:
      - HTTPBearer: []
      summary: Embeddings
      x-content-type: application/json
      x-accepts: application/json
  /submitJam/{jam_slug}/{finishedURL}/{title}:
    get:
      operationId: submit_jams_submitJam__jam_slug___finishedURL___title__get
      parameters:
      - explode: false
        in: path
        name: jam_slug
        required: true
        schema:
          title: Jam Slug
          type: string
        style: simple
      - explode: false
        in: path
        name: finishedURL
        required: true
        schema:
          title: Finishedurl
          type: string
        style: simple
      - explode: false
        in: path
        name: title
        required: true
        schema:
          title: Title
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Submit Jams
      x-accepts: application/json
  /getSubmissions:
    get:
      operationId: get_submissions_getSubmissions_get
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Get Submissions
      x-accepts: application/json
  /deleteSubmission:
    delete:
      operationId: delete_submission_deleteSubmission_delete
      parameters:
      - explode: true
        in: query
        name: url
        required: true
        schema:
          title: Url
          type: string
        style: form
      - explode: true
        in: query
        name: password
        required: true
        schema:
          title: Password
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Delete Submission
      x-accepts: application/json
components:
  schemas:
    HTTPValidationError:
      example:
        detail:
        - msg: msg
          loc:
          - ValidationError_loc_inner
          - ValidationError_loc_inner
          type: type
        - msg: msg
          loc:
          - ValidationError_loc_inner
          - ValidationError_loc_inner
          type: type
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
      title: HTTPValidationError
    ValidationError:
      example:
        msg: msg
        loc:
        - ValidationError_loc_inner
        - ValidationError_loc_inner
        type: type
      properties:
        loc:
          items:
            $ref: '#/components/schemas/ValidationError_loc_inner'
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
    ValidationError_loc_inner:
      anyOf:
      - type: string
      - type: integer
  securitySchemes:
    HTTPBearer:
      scheme: bearer
      type: http

