openapi: 3.1.0
info:
  contact:
    name: '@Cheese'
    url: https://cheese.chatango.com/
  description: deez
  license:
    name: MIT
  termsOfService: https://chatango.vissle.repl.co/policy
  title: Unofficial Chatango API
  version: 0.1.0
servers:
- url: /
paths:
  /v1/profile/{user}:
    get:
      operationId: profile_v1_profile__user__get
      parameters:
      - description: bruh moment
        explode: false
        in: path
        name: name
        required: true
        schema:
          description: bruh moment
          maxLength: 20
          minLength: 1
          title: Name
          type: string
        style: simple
      - description: Optionally set multiple queries separated by a comma.
        explode: true
        in: query
        name: get
        required: false
        schema:
          description: Optionally set multiple queries separated by a comma.
          enum:
          - mini
          - full
          - background
          - style
          - css
          - purchase
          - group
          title: Get
          type: string
        style: form
      - description: Optionally set multiple queries separated by a comma.
        explode: true
        in: query
        name: image
        required: false
        schema:
          description: Optionally set multiple queries separated by a comma.
          enum:
          - avatar
          - thumb
          - thumb_m
          - message
          - flag
          - flag_t
          - vr_t
          title: Image
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Profile
      tags:
      - api
      x-accepts: application/json
components:
  schemas:
    HTTPValidationError:
      example:
        detail:
        - msg: msg
          loc:
          - ValidationError_loc_inner
          - ValidationError_loc_inner
          type: type
        - msg: msg
          loc:
          - ValidationError_loc_inner
          - ValidationError_loc_inner
          type: type
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
      title: HTTPValidationError
    ValidationError:
      example:
        msg: msg
        loc:
        - ValidationError_loc_inner
        - ValidationError_loc_inner
        type: type
      properties:
        loc:
          items:
            $ref: '#/components/schemas/ValidationError_loc_inner'
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
    ValidationError_loc_inner:
      anyOf:
      - type: string
      - type: integer

