openapi: 3.1.0
info:
  title: Inventory Management System
  version: 1.0.0
servers:
- url: /
paths:
  /customers:
    get:
      responses:
        "200":
          description: OK
      summary: Get_Customers
      x-accepts: application/json
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
        required: true
      responses:
        "201":
          description: Created
      summary: New_Customer
      x-content-type: application/json
      x-accepts: application/json
  /customers/{customerId}:
    delete:
      parameters:
      - explode: false
        in: path
        name: customerId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "204":
          description: No Content
      summary: Delete_Customer
      x-accepts: application/json
    get:
      parameters:
      - explode: false
        in: path
        name: customerId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          description: OK
        "404":
          description: Customer not found
      summary: customerID
      x-accepts: application/json
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
        required: true
      responses:
        "200":
          description: OK
        "404":
          description: Customer not found
      summary: Update_Customer
      x-content-type: application/json
      x-accepts: application/json
  /orders:
    get:
      responses:
        "200":
          description: OK
      summary: Get_Orders
      x-accepts: application/json
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        required: true
      responses:
        "201":
          description: Created
      summary: New_Order
      x-content-type: application/json
      x-accepts: application/json
  /orders/{orderId}:
    delete:
      parameters:
      - explode: false
        in: path
        name: orderId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "204":
          description: No Content
      summary: Delete_Order
      x-accepts: application/json
    get:
      parameters:
      - explode: false
        in: path
        name: orderId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          description: OK
        "404":
          description: Order not found
      summary: OrderID
      x-accepts: application/json
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        required: true
      responses:
        "200":
          description: OK
        "404":
          description: Order not found
      summary: Update_Order
      x-content-type: application/json
      x-accepts: application/json
  /inventory:
    get:
      responses:
        "200":
          description: OK
      summary: Get_Inventory
      x-accepts: application/json
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Inventory'
        required: true
      responses:
        "201":
          description: Created
      summary: New_Inventory
      x-content-type: application/json
      x-accepts: application/json
  /inventory/{inventoryId}:
    delete:
      parameters:
      - explode: false
        in: path
        name: inventoryId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "204":
          description: No Content
      summary: Delete_Inventory
      x-accepts: application/json
    get:
      parameters:
      - explode: false
        in: path
        name: inventoryId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          description: OK
        "404":
          description: Inventory entry not found
      summary: InventoryID
      x-accepts: application/json
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Inventory'
        required: true
      responses:
        "200":
          description: OK
        "404":
          description: Inventory entry not found
      summary: Update_Inventory
      x-content-type: application/json
      x-accepts: application/json
  /items:
    get:
      responses:
        "200":
          description: OK
      summary: Get_Item
      x-accepts: application/json
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
        required: true
      responses:
        "201":
          description: Created
      summary: New_Item
      x-content-type: application/json
      x-accepts: application/json
  /items/{itemId}:
    delete:
      parameters:
      - explode: false
        in: path
        name: itemId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "204":
          description: No Content
      summary: Delete_Item
      x-accepts: application/json
    get:
      parameters:
      - explode: false
        in: path
        name: itemId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          description: OK
        "404":
          description: Item not found
      summary: ItemID
      x-accepts: application/json
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
        required: true
      responses:
        "200":
          description: OK
        "404":
          description: Item not found
      summary: Update_Item
      x-content-type: application/json
      x-accepts: application/json
components:
  schemas:
    Customer:
      example:
        phone: phone
        name: name
        id: 0
      properties:
        id:
          type: integer
        name:
          type: string
        phone:
          type: string
      required:
      - id
      - name
      - phone
    Order:
      example:
        amount: 1.4658129805029452
        orderId: 0
        customerId: 6
        orderDate: 2000-01-23
      properties:
        orderId:
          type: integer
        customerId:
          type: integer
        orderDate:
          format: date
          type: string
        amount:
          type: number
      required:
      - amount
      - customerId
      - orderDate
      - orderId
    Inventory:
      example:
        quantity: 6
        inventoryId: 0
      properties:
        inventoryId:
          type: integer
        quantity:
          type: integer
      required:
      - inventoryId
      - quantity
    Item:
      example:
        itemId: 0
        orderId: 1
        price: 6.027456183070403
        name: name
        inventoryId: 5
      properties:
        itemId:
          type: integer
        name:
          type: string
        price:
          type: number
        orderId:
          type: integer
        inventoryId:
          type: integer
      required:
      - itemId
      - name
      - orderId
      - price

