openapi: 3.0.2
info:
  contact:
    name: well-it-wasnt-me
    url: https://github.com/well-it-wasnt-me
  description: All the API used by the mobile application of Mental Space
  license:
    name: CC BY-NC-SA 4.0
    url: http://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1
  title: Mental Space Mobile API
  version: 0.0.1
externalDocs:
  description: External Documentation
  url: https://github.com/well-it-wasnt-me/mental-space-backend/wiki
servers:
- description: Local Development with php built-in server
  url: http://localhost:8080
security:
- JWT: []
paths:
  /mobile/api/mood:
    post:
      operationId: AddMoodAction
      responses:
        "200":
          description: Successful operation
      summary: Add Mood
      tags:
      - Mood Management
      x-accepts: application/json
  /mobile/api/mood/delete/{mood_id}:
    get:
      operationId: DeleteMoodAction
      parameters:
      - explode: false
        in: path
        name: mood_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
      summary: Delete Mood
      tags:
      - Mood Management
      x-accepts: application/json
  /mobile/api/last_10_mood:
    get:
      operationId: ListMoodAction
      responses:
        "200":
          description: Successful operation
      summary: List Last 10 Moods
      tags:
      - Mood Management
      x-accepts: application/json
  /mobile/api/last_10_mood/graph:
    get:
      operationId: ListMoodGraphAction
      responses:
        "200":
          description: Successful operation
      summary: List Mood Graph
      tags:
      - Mood Management
      x-accepts: application/json
  /mobile/api/patient/update:
    post:
      operationId: UserUpdateAction
      responses:
        "200":
          description: Successful operation
      summary: Update Patient
      tags:
      - Patient Management
      x-accepts: application/json
  /mobile/api/patient/update/address:
    post:
      operationId: UserUpdateAddrAction
      responses:
        "200":
          description: Successful operation
      summary: Update Patient Address
      tags:
      - Patient Management
      x-accepts: application/json
  /mobile/api/invite/doctor:
    post:
      operationId: InviteDoctorAction
      responses:
        "200":
          description: Successful operation
      summary: Invite Doctor
      tags:
      - Patient Management
      x-accepts: application/json
  /mobile/api/patient/my_doctor:
    get:
      operationId: DocDetailAppAction
      responses:
        "200":
          description: Successful operation
      summary: Get Patient's Doctor
      tags:
      - Patient Management
      x-accepts: application/json
  /mobile/api/patient/scollega_doc:
    get:
      operationId: DocRemoveAction
      responses:
        "200":
          description: Successful operation
      summary: Remove Doctor
      tags:
      - Patient Management
      x-accepts: application/json
  /mobile/api/patient/delete_account:
    get:
      responses:
        "200":
          description: Successful operation
      summary: Delete Patient Account
      tags:
      - Patient Management
      x-accepts: application/json
  /mobile/api/drugs/list:
    get:
      operationId: MobileListPharmAction
      responses:
        "200":
          description: Successful operation
      summary: List Drugs
      tags:
      - Drugs Management
      x-accepts: application/json
  /mobile/api/drugs/list/search/{drug_name}:
    get:
      operationId: SearchByNameAction
      parameters:
      - explode: false
        in: path
        name: drug_name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
      summary: Search Drugs by Name
      tags:
      - Drugs Management
      x-accepts: application/json
  /mobile/api/patient/diary:
    get:
      operationId: GetDiaryAction
      responses:
        "200":
          content:
            application/json:
              example:
                status: success
                message: Operation successful
          description: Successful operation
      summary: Get Patient Diary
      tags:
      - Patient Management
      - Diary Management
      x-accepts: application/json
    post:
      operationId: UploadDiaryAction
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UploadDiaryAction_request'
        required: true
      responses:
        "200":
          content:
            application/json:
              example:
                status: success
                message: Operation successful
          description: Successful operation
        default:
          content:
            application/json:
              example:
                status: error
                message: Something went wrong
          description: Error
      summary: Upload Diary
      tags:
      - Patient Management
      - Diary Management
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /mobile/api/patient/diary/delete/{diary_id}:
    get:
      operationId: DeleteDiaryAction
      parameters:
      - explode: false
        in: path
        name: diary_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
      summary: Delete Diary Entry
      tags:
      - Patient Management
      x-accepts: application/json
  /mobile/api/patient/file/upload:
    post:
      operationId: FileUploadAction
      responses:
        "200":
          description: Successful operation
      summary: Upload File
      tags:
      - Patient Management
      x-accepts: application/json
  /mobile/api/patient/file/list:
    get:
      operationId: FileListAction
      responses:
        "200":
          description: Successful operation
      summary: List Files
      tags:
      - Patient Management
      x-accepts: application/json
  /mobile/api/patient/file/download:
    post:
      operationId: FileDownloadAction
      responses:
        "200":
          description: Successful operation
      summary: Download File
      tags:
      - Patient Management
      x-accepts: application/json
  /mobile/api/patient/tracking:
    post:
      operationId: UserTrackAction
      responses:
        "200":
          description: Successful operation
      summary: Track User
      tags:
      - Patient Management
      x-accepts: application/json
  /mobile/api/patient/tracking/list:
    get:
      operationId: UserTrackListAction
      responses:
        "200":
          description: Successful operation
      summary: List User Tracking
      tags:
      - Patient Management
      x-accepts: application/json
  /mobile/api/patient/calendar:
    get:
      operationId: UserCalendarAction
      responses:
        "200":
          description: Successful operation
      summary: Get User Calendar
      tags:
      - Patient Management
      x-accepts: application/json
  /mobile/api/patient/drug/list:
    get:
      operationId: ListPharmPatientMobAction
      responses:
        "200":
          description: Successful operation
      summary: List Patient Drugs
      tags:
      - Patient Management
      x-accepts: application/json
  /mobile/api/patient/drug/delete/{id}:
    get:
      operationId: DeletePharmAction
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Successful operation
      summary: Delete Patient Drug
      tags:
      - Patient Management
      x-accepts: application/json
  /mobile/api/patient/drug/add:
    post:
      operationId: AddPharmAction
      responses:
        "200":
          description: Successful operation
      summary: Add Patient Drug
      tags:
      - Patient Management
      x-accepts: application/json
  /mobile/api/patient/account/delete:
    get:
      operationId: UserDeleteAction
      responses:
        "200":
          description: Successful operation
      summary: Delete Patient Account
      tags:
      - Patient Management
      x-accepts: application/json
  /mobile/api/patient/account/download:
    get:
      operationId: UserDownloadAction
      responses:
        "200":
          description: Successful operation
      summary: Download Patient Account
      tags:
      - Patient Management
      x-accepts: application/json
  /mobile/api/obiettivi/add:
    post:
      operationId: AddObjectiveAction
      responses:
        "200":
          description: Successful operation
      summary: Add Objective
      tags:
      - Objective Management
      x-accepts: application/json
  /mobile/api/obiettivi/delete:
    post:
      operationId: DeleteObjectiveAction
      responses:
        "200":
          description: Successful operation
      summary: Delete Objective
      tags:
      - Objective Management
      x-accepts: application/json
  /mobile/api/obiettivi/update:
    post:
      operationId: UpdateObjectiveAction
      responses:
        "200":
          description: Successful operation
      summary: Update Objective
      tags:
      - Objective Management
      x-accepts: application/json
  /mobile/api/obiettivi/list:
    get:
      operationId: ListObjectiveAction
      responses:
        "200":
          description: Successful operation
      summary: List Objectives
      tags:
      - Objective Management
      x-accepts: application/json
  /mobile/api/patient/report/pills:
    get:
      operationId: ReportGenAction
      responses:
        "200":
          description: Successful operation
      summary: Generate and send mail about actual drug treatment
      tags:
      - Report
      x-accepts: application/json
  /mobile/api/patient/report/mood:
    post:
      operationId: ReportMoodGenAction
      responses:
        "200":
          description: Successful operation
      summary: Generate and send mail about actual mood
      tags:
      - Report
      x-accepts: application/json
  /mobile/api/patient/test/comportamento:
    get:
      operationId: ListBehaviourTestAction
      responses:
        "200":
          description: Successful operation
      summary: List behaviour test
      tags:
      - Tests
      x-accepts: application/json
    post:
      operationId: BehaviourTestAction
      responses:
        "200":
          description: Successful operation
      summary: Receive user input from behaviour
      tags:
      - Report
      x-accepts: application/json
  /mobile/api/patient/test/emozioni:
    get:
      operationId: ListEmotionsTestAction
      responses:
        "200":
          description: Successful operation
      summary: List emotions test
      tags:
      - Tests
      x-accepts: application/json
    post:
      operationId: EmotionsTestAction
      responses:
        "200":
          description: Successful operation
      summary: Receive user input from behaviour
      tags:
      - Tests
      x-accepts: application/json
  /mobile/api/patient/health/passi:
    post:
      operationId: AddStepsAction
      responses:
        "200":
          description: Successful operation
      summary: Submit user steps
      tags:
      - Health
      x-accepts: application/json
  /mobile/api/patient/test/phq:
    get:
      operationId: ListPhq9TestAction
      responses:
        "200":
          description: Successful operation
      summary: Return depression submitted test
      tags:
      - Tests
      x-accepts: application/json
    post:
      operationId: Phq9TestAction
      responses:
        "200":
          description: Successful operation
      summary: Submit user test on depression
      tags:
      - Tests
      x-accepts: application/json
  /mobile/api/register/notification:
    post:
      operationId: RegisterNotificationAction
      responses:
        "200":
          description: Successful operation
      summary: Register user for in app notification
      tags:
      - Notifications
      x-accepts: application/json
components:
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  schemas:
    UploadDiaryAction_request:
      properties:
        diario:
          description: Long text (possibly in HTML)
          type: string
      required:
      - diario
      type: object
  securitySchemes:
    JWT:
      bearerFormat: JWT
      description: JWT received at login
      in: header
      scheme: bearer
      type: http

