openapi: 3.0.0
info:
  description: API spec for node-proxy endpoint
  title: node-proxy
  version: 1.0.0
servers:
- url: /
paths:
  /idrac:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_idrac_post_request'
        required: true
      responses:
        "200":
          description: "Success, return idrac details."
        "400":
          description: Some fields are missing in the provided data.
        "403":
          description: Invalid keyring provided.
        "502":
          description: The cephadm agent isn't running on the node.
      summary: Get the iDrac details for a given host.
      x-content-type: application/json
      x-accepts: application/json
  /data:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_data_post_request'
        required: true
      responses:
        "200":
          description: "Success, data processed."
        "400":
          description: Some fields are missing in the provided data.
        "403":
          description: Invalid keyring provided.
      summary: Handles incoming data and process them.
      x-content-type: application/json
      x-accepts: application/json
  /{hostname}/led:
    get:
      parameters:
      - explode: false
        in: path
        name: hostname
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: "Success, led current status returned."
      summary: Get the current state of enclosure LED for the specified hostname.
      x-accepts: application/json
    patch:
      parameters:
      - explode: false
        in: path
        name: hostname
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/__hostname__led_patch_request'
        required: true
      responses:
        "200":
          description: "Success, led state changed."
        "400":
          description: Some fields are missing in the provided data.
        "403":
          description: Invalid keyring provided.
        "501":
          description: No hostname has been passed. (Not implemented)
        "502":
          description: The endpoint is unreachable.
      summary: Set enclosure LED status for the specified hostname.
      x-content-type: application/json
      x-accepts: application/json
  /{hostname}/fullreport:
    get:
      parameters:
      - explode: false
        in: path
        name: hostname
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: "Success, full report returned."
        "404":
          description: The passed hostname was not found.
      summary: Get the full report.
      x-accepts: application/json
  /{hostname}/summary:
    get:
      parameters:
      - explode: false
        in: path
        name: hostname
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: "Success, summary report returned."
        "404":
          description: The passed hostname was not found.
      summary: Get the a brief summary of hardware status.
      x-accepts: application/json
  /{hostname}/criticals:
    get:
      parameters:
      - explode: false
        in: path
        name: hostname
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: "Success, critical report returned."
        "404":
          description: The passed hostname was not found.
      summary: Get the report of critical components.
      x-accepts: application/json
  /{hostname}/memory:
    get:
      parameters:
      - explode: false
        in: path
        name: hostname
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: "Success, memory report returned."
        "404":
          description: The passed hostname was not found.
      summary: Get the memory report.
      x-accepts: application/json
  /{hostname}/network:
    get:
      parameters:
      - explode: false
        in: path
        name: hostname
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: "Success, report for network hardware returned."
        "404":
          description: The passed hostname was not found.
      summary: Get the report for network hardware.
      x-accepts: application/json
  /{hostname}/processors:
    get:
      parameters:
      - explode: false
        in: path
        name: hostname
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: "Success, cpu report returned."
        "404":
          description: The passed hostname was not found.
      summary: Get the cpu report.
      x-accepts: application/json
  /{hostname}/storage:
    get:
      parameters:
      - explode: false
        in: path
        name: hostname
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: "Success, storage disks report returned."
        "404":
          description: The passed hostname was not found.
      summary: Get the storage disks report for.
      x-accepts: application/json
  /{hostname}/power:
    get:
      parameters:
      - explode: false
        in: path
        name: hostname
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: "Success, power supply hardware report returned."
        "404":
          description: The passed hostname was not found.
      summary: Get the power supply report.
      x-accepts: application/json
  /{hostname}/fans:
    get:
      parameters:
      - explode: false
        in: path
        name: hostname
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: "Success, fan report returned."
        "404":
          description: The passed hostname was not found.
      summary: Get the fan report.
      x-accepts: application/json
  /{hostname}/firmwares:
    get:
      parameters:
      - explode: false
        in: path
        name: hostname
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: "Success, firmware report returned."
        "404":
          description: The passed hostname was not found.
      summary: Get the firmware report.
      x-accepts: application/json
components:
  schemas:
    _idrac_post_request:
      properties:
        cephx:
          $ref: '#/components/schemas/_idrac_post_request_cephx'
        name:
          type: string
      type: object
    __hostname__led_patch_request:
      properties:
        cephx:
          $ref: '#/components/schemas/_idrac_post_request_cephx'
        name:
          type: string
        IndicatorLED:
          type: string
      type: object
    _idrac_post_request_cephx:
      properties:
        name:
          type: string
        secret:
          type: string
      type: object
    _data_post_request:
      properties:
        cephx:
          $ref: '#/components/schemas/_idrac_post_request_cephx'
        name:
          type: string
        patch:
          type: object
      type: object

