name: Redoc
'on':
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch: null
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate Redoc static HTML
        run: |
          npx @redocly/cli build-docs openbanking-us.yaml --output openbanking-us.html
      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: openbanking-us.html
          path: ./openbanking-us.html
