name: Java CI with Maven

on:
  push:
    branches: [ "master", "develop", "*" ]
  pull_request:
    branches: [ "master", "develop" , "*"]
  workflow_dispatch:
    inputs:
      generatorInputSpec:
        description: 'OpenAPI document to generate code from'
        required: true

jobs:
  Run-OpenAPI-Generator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        chmod +x ./bin/override-generator-input.sh
        ./bin/override-generator-input.sh ${{ github.event.inputs.generatorInputSpec }}
    - name: Commit and push changes
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add ./gen/*
        git commit -m "Update generated files"
        git push